In [55]:
#importing  library
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression,LogisticRegressionCV

In [56]:
#loading the dataset
df=pd.read_csv('../input/apple-store-ranks-2019/ranks.csv')
#showing the dataset
df

,appid,date,category,feed,name,publisher,price,ranking,change,sub_ranking,sub_change,comment_rating,comment_num,keyword_cover
0,691828408,2019-11-30,5000,free,微视-短视频创作与分享,Tencent Technology (Beijing) Company Limited,0.0,1,12,1,5,4.5,124000,17503
1,1458072671,2019-11-30,5000,free,剪映 - 轻而易剪,深圳市脸萌科技有限公司,0.0,2,-1,2,-1,4.9,632000,19978
2,1448327606,2019-11-30,5000,free,刷宝短视频,成都力奥文化传播有限公司,0.0,3,-1,3,-1,4.8,599000,6759
3,1472502819,2019-11-30,5000,free,快手极速版,华艺汇龙,0.0,4,-1,4,-1,4.9,228000,38549
4,1142110895,2019-11-30,5000,free,抖音短视频,"Beijing Microlive Vision Technology Co., Ltd",0.0,5,-1,5,-1,4.9,23870000,21441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112622,1142972033,2019-12-06,5000,grossing,漫画岛-快看二次元动漫漫画神器APP,上海元聚网络科技有限公司,0.0,634,9999,62,3,4.6,2747,5457
112623,1196953001,2019-12-06,5000,grossing,SuperPads打击垫：音乐魔器,Opala Studios Solucoes Tecnologicas Ltda,0.0,635,9999,26,4,4.7,30500,5297
112624,487115059,2019-12-06,5000,grossing,7M即时比分-足球探索预测分析体育网,IEXIN Technology Development Limited,0.0,636,9999,19,0,4.9,3552,17844
112625,493145008,2019-12-06,5000,grossing,Headspace: Meditation & Sleep,Headspace Inc.,0.0,637,9999,20,3,4.9,3658,1968
112626,1468605335,2019-12-06,5000,grossing,草莓交友-同城视频聊天交友约会,siqi xie,0.0,638,9999,89,17,5.0,4244,6180

In [57]:
#getting information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112627 entries, 0 to 112626
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   appid           112627 non-null  int64
 1   date            112627 non-null  object
 2   category        112627 non-null  int64
 3   feed            112627 non-null  object
 4   name            112627 non-null  object
 5   publisher       112627 non-null  object
 6   price           112627 non-null  float64
 7   ranking         112627 non-null  int64
 8   change          112627 non-null  int64
 9   sub_ranking     112627 non-null  int64
 10  sub_change      112627 non-null  int64
 11  comment_rating  112627 non-null  float64
 12  comment_num     112627 non-null  int64
 13  keyword_cover   112627 non-null  int64
dtypes: float64(2), int64(8), object(4)
memory usage: 12.0+ MB

In [58]:
#iunneeded columns
unneeded_column=['appid','name','publisher']
df=df.drop(unneeded_column,axis=1)

In [59]:
#checking for null values 
df.isna().sum()

date              0
category          0
feed              0
price             0
ranking           0
change            0
sub_ranking       0
sub_change        0
comment_rating    0
comment_num       0
keyword_cover     0
dtype: int64

In [60]:
 #checking for missing values
print('Total Missing Values',df.isna().sum().sum())

Total Missing Values 0

In [61]:
df['year']=df['date'].apply(lambda x:np.int(x[0:4]))
df['month']=df['date'].apply(lambda x:np.int(x[5:7]))
df['day']=df['date'].apply(lambda x:np.int(x[-2:]))

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until

In [62]:
#dropping the original day column
df=df.drop('date',axis=1)

In [63]:
df

,category,feed,price,ranking,change,sub_ranking,sub_change,comment_rating,comment_num,keyword_cover,year,month,day
0,5000,free,0.0,1,12,1,5,4.5,124000,17503,2019,11,30
1,5000,free,0.0,2,-1,2,-1,4.9,632000,19978,2019,11,30
2,5000,free,0.0,3,-1,3,-1,4.8,599000,6759,2019,11,30
3,5000,free,0.0,4,-1,4,-1,4.9,228000,38549,2019,11,30
4,5000,free,0.0,5,-1,5,-1,4.9,23870000,21441,2019,11,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112622,5000,grossing,0.0,634,9999,62,3,4.6,2747,5457,2019,12,6
112623,5000,grossing,0.0,635,9999,26,4,4.7,30500,5297,2019,12,6
112624,5000,grossing,0.0,636,9999,19,0,4.9,3552,17844,2019,12,6
112625,5000,grossing,0.0,637,9999,20,3,4.9,3658,1968,2019,12,6
112626,5000,grossing,0.0,638,9999,89,17,5.0,4244,6180,2019,12,6

In [64]:
df['category'].unique()

array([5000, 6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6009,
       6010, 6011, 6012, 6013, 6015, 6016, 6017, 6018, 6020, 6021, 6023,
       6024, 6061])

In [65]:
#creating dummies
category_dummies=pd.get_dummies(df['category'])

In [66]:
#concating the dummies with original column
df=pd.concat([df,category_dummies],axis=1)

In [67]:
#dropping original category columns
df=df.drop('category',axis=1)

Encoding Labels

In [68]:
df['feed'].value_counts()

free        40677
paid        36709
grossing    35241
Name: feed, dtype: int64

In [69]:
#querying
grossing_index=df.query("feed=='grossing'").index

In [70]:
#dropping the grossing index
df=df.drop(grossing_index,axis=0).reset_index(drop=True)

In [71]:
df

,feed,price,ranking,change,sub_ranking,sub_change,comment_rating,comment_num,keyword_cover,year,...,6013,6015,6016,6017,6018,6020,6021,6023,6024,6061
0,free,0.0,1,12,1,5,4.5,124000,17503,2019,...,0,0,0,0,0,0,0,0,0,0
1,free,0.0,2,-1,2,-1,4.9,632000,19978,2019,...,0,0,0,0,0,0,0,0,0,0
2,free,0.0,3,-1,3,-1,4.8,599000,6759,2019,...,0,0,0,0,0,0,0,0,0,0
3,free,0.0,4,-1,4,-1,4.9,228000,38549,2019,...,0,0,0,0,0,0,0,0,0,0
4,free,0.0,5,-1,5,-1,4.9,23870000,21441,2019,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77381,paid,6.0,786,9999,128,35,0.0,0,685,2019,...,0,0,0,0,0,0,0,0,0,0
77382,paid,1.0,787,-79,32,-4,0.0,0,1142,2019,...,0,0,0,0,0,0,0,0,0,0
77383,paid,25.0,788,-72,22,-2,4.5,132,1240,2019,...,0,0,0,0,0,0,0,0,0,0
77384,paid,12.0,789,-54,84,-7,4.8,744,477,2019,...,0,0,0,0,0,0,0,0,0,0
77385,paid,1.0,790,-80,159,-12,4.0,15,192,2019,...,0,0,0,0,0,0,0,0,0,0

In [75]:
#getting class distribution
df['feed'].value_counts()

free    40677
paid    36709
Name: feed, dtype: int64

In [76]:
print('Class Distribution')
print(df['feed'].value_counts()/len(df['feed']))

Class Distribution
free    0.525638
paid    0.474362
Name: feed, dtype: float64

In [74]:
#mapping values
label_mapping={'free':0,'paid':1}
label_mapping

{'free': 0, 'paid': 1}

In [78]:
df['feed']=df['feed'].replace(label_mapping)

In [80]:
df

,feed,price,ranking,change,sub_ranking,sub_change,comment_rating,comment_num,keyword_cover,year,...,6013,6015,6016,6017,6018,6020,6021,6023,6024,6061
0,0,0.0,1,12,1,5,4.5,124000,17503,2019,...,0,0,0,0,0,0,0,0,0,0
1,0,0.0,2,-1,2,-1,4.9,632000,19978,2019,...,0,0,0,0,0,0,0,0,0,0
2,0,0.0,3,-1,3,-1,4.8,599000,6759,2019,...,0,0,0,0,0,0,0,0,0,0
3,0,0.0,4,-1,4,-1,4.9,228000,38549,2019,...,0,0,0,0,0,0,0,0,0,0
4,0,0.0,5,-1,5,-1,4.9,23870000,21441,2019,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77381,1,6.0,786,9999,128,35,0.0,0,685,2019,...,0,0,0,0,0,0,0,0,0,0
77382,1,1.0,787,-79,32,-4,0.0,0,1142,2019,...,0,0,0,0,0,0,0,0,0,0
77383,1,25.0,788,-72,22,-2,4.5,132,1240,2019,...,0,0,0,0,0,0,0,0,0,0
77384,1,12.0,789,-54,84,-7,4.8,744,477,2019,...,0,0,0,0,0,0,0,0,0,0
77385,1,1.0,790,-80,159,-12,4.0,15,192,2019,...,0,0,0,0,0,0,0,0,0,0

# #Splitting and Scaling the DataSet

In [90]:
#spliting the dataframe to x and y
y=df['feed'].copy()
x=df.drop('feed',axis=1).copy()

In [82]:
#scaling the dataset
scaler=StandardScaler()
x=scaler.fit_transform(x)

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

In [85]:
#train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=34)

In [87]:
#training the model
#creating instance of LogisticRegression class
base_model=LogisticRegression()
#apply attributes to the instances base_model
base_model.fit(x_train,y_train)
base_acc=base_model.score(x_test,y_test)

In [88]:
#PRINTING THE ACCURACY
print('Accuracy:{:4f}'.format(base_acc))

Accuracy:0.975879

In [89]:
#creating new instance
cv_model=LogisticRegressionCV()
cv_model.fit(x_train,y_train)
cv_acc=cv_model.score(x_test,y_test)
print('Accuray:{:.4f}',format(cv_acc))

Accuray:{:.4f} 0.9995692625775328