In [297]:
#importing library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [258]:
#showing the dataset
df=pd.read_csv('../input/nifty500-stocks-dataset/nifty_500.csv')
#loading the dataset
df

,Company Name,Symbol,Industry,Series,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,365 Day Percentage Change,30 Day Percentage Change
0,3M India Ltd.,3MINDIA,Diversified,EQ,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,17273.00,-10.18,8.22
1,Aarti Drugs Ltd.,AARTIDRUGS,Healthcare,EQ,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,378.00,-42.92,-5.10
2,Aavas Financiers Ltd.,AAVAS,Financial Services,EQ,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,1815.00,-25.69,-9.39
3,ABB India Ltd.,ABB,Capital Goods,EQ,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,1618.05,27.25,-5.21
4,Abbott India Ltd.,ABBOTINDIA,Healthcare,EQ,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,15514.00,11.61,5.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,Zensar Technolgies Ltd.,ZENSARTECH,Information Technology,EQ,273.15,273.55,268.40,272.10,270.00,-2.10,-0.77,186578,5.046748e+07,587.00,246.65,-12.61,-11.02
497,ZF Commercial Vehicle Control Systems India Ltd.,ZFCVINDIA,Automobile and Auto Components,EQ,7748.00,7900.00,7525.30,7716.60,7680.00,-36.60,-0.47,12790,9.884624e+07,8780.05,6793.30,-,1.43
498,Zomato Ltd.,ZOMATO,Consumer Services,EQ,54.15,56.70,52.55,53.85,56.00,2.15,3.99,112078641,6.193466e+09,169.00,50.05,-,-27.86
499,Zydus Lifesciences Ltd.,ZYDUSLIFE,Healthcare,EQ,356.90,364.05,354.30,357.00,364.00,7.00,1.96,862373,3.100145e+08,651.90,319.00,-,-5.64
500,Zydus Wellness Ltd.,ZYDUSWELL,Fast Moving Consumer Goods,EQ,1635.00,1635.00,1605.00,1636.85,1627.00,-9.85,-0.60,10803,1.749567e+07,2476.85,1430.00,-22.08,6.25

In [259]:
#getting information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Name               501 non-null    object
 1   Symbol                     501 non-null    object
 2   Industry                   501 non-null    object
 3   Series                     501 non-null    object
 4   Open                       501 non-null    float64
 5   High                       501 non-null    float64
 6   Low                        501 non-null    float64
 7   Previous Close             501 non-null    float64
 8   Last Traded Price          501 non-null    float64
 9   Change                     501 non-null    object
 10  Percentage Change          501 non-null    object
 11  Share Volume               501 non-null    int64
 12  Value (Indian Rupee)       501 non-null    float64
 13  52 Week High               501 non-null    float64
 14  52 Week Low                501 non-null    float64
 15  365 Day Percentage Change  501 non-null    object
 16  30 Day Percentage Change   501 non-null    object
dtypes: float64(8), int64(1), object(8)
memory usage: 66.7+ KB

In [260]:
#dropping the unnecessary columns
df=df.drop('Company Name',axis=1)

In [261]:
#dropping the Symbol column
df=df.drop('Symbol',axis=1)

In [262]:
df['Industry'].value_counts()

Financial Services                   88
Healthcare                           52
Capital Goods                        48
Chemicals                            38
Fast Moving Consumer Goods           33
Information Technology               29
Consumer Durables                    28
Automobile and Auto Components       27
Consumer Services                    24
Services                             21
Oil Gas & Consumable Fuels           17
Construction                         14
Metals & Mining                      14
Construction Materials               13
Power                                11
Realty                               11
Textiles                             10
Telecommunication                    10
Media Entertainment & Publication     9
Forest Materials                      2
Diversified                           2
Name: Industry, dtype: int64

In [263]:
#onehot encoding the Industry column
#df=pd.get_dummies('Industry')

In [264]:
dummies=pd.get_dummies(df['Industry'])

In [265]:
#concating the dummies with original dataframe
df=pd.concat([df,dummies],axis=1)

In [266]:
#dropping the original column
df=df.drop('Industry',axis=1)

In [267]:
#dropping the Series Column
df=df.drop('Series',axis=1)

In [268]:
df

,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,...,Healthcare,Information Technology,Media Entertainment & Publication,Metals & Mining,Oil Gas & Consumable Fuels,Power,Realty,Services,Telecommunication,Textiles
0,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,...,0,0,0,0,0,0,0,0,0,0
1,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,...,1,0,0,0,0,0,0,0,0,0
2,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,...,0,0,0,0,0,0,0,0,0,0
3,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,...,0,0,0,0,0,0,0,0,0,0
4,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,273.15,273.55,268.40,272.10,270.00,-2.10,-0.77,186578,5.046748e+07,587.00,...,0,1,0,0,0,0,0,0,0,0
497,7748.00,7900.00,7525.30,7716.60,7680.00,-36.60,-0.47,12790,9.884624e+07,8780.05,...,0,0,0,0,0,0,0,0,0,0
498,54.15,56.70,52.55,53.85,56.00,2.15,3.99,112078641,6.193466e+09,169.00,...,0,0,0,0,0,0,0,0,0,0
499,356.90,364.05,354.30,357.00,364.00,7.00,1.96,862373,3.100145e+08,651.90,...,1,0,0,0,0,0,0,0,0,0
500,1635.00,1635.00,1605.00,1636.85,1627.00,-9.85,-0.60,10803,1.749567e+07,2476.85,...,0,0,0,0,0,0,0,0,0,0

In [269]:
#checking for null value
df.isna().sum().sum()

0

In [270]:
#splitting the datset into x and y

In [271]:
#creating new colum from existing one
df['Target']=df.Open.shift(-1)

In [272]:
df

,Open,High,Low,Previous Close,Last Traded Price,Change,Percentage Change,Share Volume,Value (Indian Rupee),52 Week High,...,Information Technology,Media Entertainment & Publication,Metals & Mining,Oil Gas & Consumable Fuels,Power,Realty,Services,Telecommunication,Textiles,Target
0,21950.00,21999.00,21126.05,21854.05,21575.00,-279.05,-1.28,4159,8.965357e+07,27800.00,...,0,0,0,0,0,0,0,0,0,400.50
1,400.50,401.80,394.10,403.85,400.00,-3.85,-0.95,31782,1.262731e+07,749.75,...,0,0,0,0,0,0,0,0,0,1997.10
2,1997.10,2004.05,1894.50,2015.45,1943.15,-72.30,-3.59,150704,2.907728e+08,3340.00,...,0,0,0,0,0,0,0,0,0,2260.35
3,2260.35,2311.50,2260.35,2300.90,2280.00,-20.90,-0.91,97053,2.210935e+08,2487.85,...,0,0,0,0,0,0,0,0,0,18700.40
4,18700.40,19200.00,18605.00,18760.40,19199.80,439.40,2.34,12396,2.346770e+08,23934.45,...,0,0,0,0,0,0,0,0,0,89.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,273.15,273.55,268.40,272.10,270.00,-2.10,-0.77,186578,5.046748e+07,587.00,...,1,0,0,0,0,0,0,0,0,7748.00
497,7748.00,7900.00,7525.30,7716.60,7680.00,-36.60,-0.47,12790,9.884624e+07,8780.05,...,0,0,0,0,0,0,0,0,0,54.15
498,54.15,56.70,52.55,53.85,56.00,2.15,3.99,112078641,6.193466e+09,169.00,...,0,0,0,0,0,0,0,0,0,356.90
499,356.90,364.05,354.30,357.00,364.00,7.00,1.96,862373,3.100145e+08,651.90,...,0,0,0,0,0,0,0,0,0,1635.00
500,1635.00,1635.00,1605.00,1636.85,1627.00,-9.85,-0.60,10803,1.749567e+07,2476.85,...,0,0,0,0,0,0,0,0,0,NaN

In [273]:
#spliting the dataset into x and y
y=df['Target']

In [274]:
x=df.drop('Target',axis=1)

In [275]:
#transforming the dataset
scaler=StandardScaler()
scaler.fit_transform(x)

ValueError: could not convert string to float: '-'

In [276]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 35 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Open                               501 non-null    float64
 1   High                               501 non-null    float64
 2   Low                                501 non-null    float64
 3   Previous Close                     501 non-null    float64
 4   Last Traded Price                  501 non-null    float64
 5   Change                             501 non-null    object
 6   Percentage Change                  501 non-null    object
 7   Share Volume                       501 non-null    int64
 8   Value (Indian Rupee)               501 non-null    float64
 9   52 Week High                       501 non-null    float64
 10  52 Week Low                        501 non-null    float64
 11  365 Day Percentage Change          501 non-null    object
 12  30 Day Percentage Change           501 non-null    object
 13  Automobile and Auto Components     501 non-null    uint8
 14  Capital Goods                      501 non-null    uint8
 15  Chemicals                          501 non-null    uint8
 16  Construction                       501 non-null    uint8
 17  Construction Materials             501 non-null    uint8
 18  Consumer Durables                  501 non-null    uint8
 19  Consumer Services                  501 non-null    uint8
 20  Diversified                        501 non-null    uint8
 21  Fast Moving Consumer Goods         501 non-null    uint8
 22  Financial Services                 501 non-null    uint8
 23  Forest Materials                   501 non-null    uint8
 24  Healthcare                         501 non-null    uint8
 25  Information Technology             501 non-null    uint8
 26  Media Entertainment & Publication  501 non-null    uint8
 27  Metals & Mining                    501 non-null    uint8
 28  Oil Gas & Consumable Fuels         501 non-null    uint8
 29  Power                              501 non-null    uint8
 30  Realty                             501 non-null    uint8
 31  Services                           501 non-null    uint8
 32  Telecommunication                  501 non-null    uint8
 33  Textiles                           501 non-null    uint8
 34  Target                             500 non-null    float64
dtypes: float64(9), int64(1), object(4), uint8(21)
memory usage: 65.2+ KB

In [278]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 35 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Open                               501 non-null    float64
 1   High                               501 non-null    float64
 2   Low                                501 non-null    float64
 3   Previous Close                     501 non-null    float64
 4   Last Traded Price                  501 non-null    float64
 5   Change                             501 non-null    object
 6   Percentage Change                  501 non-null    object
 7   Share Volume                       501 non-null    int64
 8   Value (Indian Rupee)               501 non-null    float64
 9   52 Week High                       501 non-null    float64
 10  52 Week Low                        501 non-null    float64
 11  365 Day Percentage Change          501 non-null    object
 12  30 Day Percentage Change           501 non-null    object
 13  Automobile and Auto Components     501 non-null    uint8
 14  Capital Goods                      501 non-null    uint8
 15  Chemicals                          501 non-null    uint8
 16  Construction                       501 non-null    uint8
 17  Construction Materials             501 non-null    uint8
 18  Consumer Durables                  501 non-null    uint8
 19  Consumer Services                  501 non-null    uint8
 20  Diversified                        501 non-null    uint8
 21  Fast Moving Consumer Goods         501 non-null    uint8
 22  Financial Services                 501 non-null    uint8
 23  Forest Materials                   501 non-null    uint8
 24  Healthcare                         501 non-null    uint8
 25  Information Technology             501 non-null    uint8
 26  Media Entertainment & Publication  501 non-null    uint8
 27  Metals & Mining                    501 non-null    uint8
 28  Oil Gas & Consumable Fuels         501 non-null    uint8
 29  Power                              501 non-null    uint8
 30  Realty                             501 non-null    uint8
 31  Services                           501 non-null    uint8
 32  Telecommunication                  501 non-null    uint8
 33  Textiles                           501 non-null    uint8
 34  Target                             500 non-null    float64
dtypes: float64(9), int64(1), object(4), uint8(21)
memory usage: 65.2+ KB

In [279]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 35 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Open                               501 non-null    float64
 1   High                               501 non-null    float64
 2   Low                                501 non-null    float64
 3   Previous Close                     501 non-null    float64
 4   Last Traded Price                  501 non-null    float64
 5   Change                             501 non-null    object
 6   Percentage Change                  501 non-null    object
 7   Share Volume                       501 non-null    int64
 8   Value (Indian Rupee)               501 non-null    float64
 9   52 Week High                       501 non-null    float64
 10  52 Week Low                        501 non-null    float64
 11  365 Day Percentage Change          501 non-null    object
 12  30 Day Percentage Change           501 non-null    object
 13  Automobile and Auto Components     501 non-null    uint8
 14  Capital Goods                      501 non-null    uint8
 15  Chemicals                          501 non-null    uint8
 16  Construction                       501 non-null    uint8
 17  Construction Materials             501 non-null    uint8
 18  Consumer Durables                  501 non-null    uint8
 19  Consumer Services                  501 non-null    uint8
 20  Diversified                        501 non-null    uint8
 21  Fast Moving Consumer Goods         501 non-null    uint8
 22  Financial Services                 501 non-null    uint8
 23  Forest Materials                   501 non-null    uint8
 24  Healthcare                         501 non-null    uint8
 25  Information Technology             501 non-null    uint8
 26  Media Entertainment & Publication  501 non-null    uint8
 27  Metals & Mining                    501 non-null    uint8
 28  Oil Gas & Consumable Fuels         501 non-null    uint8
 29  Power                              501 non-null    uint8
 30  Realty                             501 non-null    uint8
 31  Services                           501 non-null    uint8
 32  Telecommunication                  501 non-null    uint8
 33  Textiles                           501 non-null    uint8
 34  Target                             500 non-null    float64
dtypes: float64(9), int64(1), object(4), uint8(21)
memory usage: 65.2+ KB

In [280]:
df=df.drop('Change',axis=1)

In [281]:
df=df.drop('Percentage Change',axis=1)

In [282]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 33 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Open                               501 non-null    float64
 1   High                               501 non-null    float64
 2   Low                                501 non-null    float64
 3   Previous Close                     501 non-null    float64
 4   Last Traded Price                  501 non-null    float64
 5   Share Volume                       501 non-null    int64
 6   Value (Indian Rupee)               501 non-null    float64
 7   52 Week High                       501 non-null    float64
 8   52 Week Low                        501 non-null    float64
 9   365 Day Percentage Change          501 non-null    object
 10  30 Day Percentage Change           501 non-null    object
 11  Automobile and Auto Components     501 non-null    uint8
 12  Capital Goods                      501 non-null    uint8
 13  Chemicals                          501 non-null    uint8
 14  Construction                       501 non-null    uint8
 15  Construction Materials             501 non-null    uint8
 16  Consumer Durables                  501 non-null    uint8
 17  Consumer Services                  501 non-null    uint8
 18  Diversified                        501 non-null    uint8
 19  Fast Moving Consumer Goods         501 non-null    uint8
 20  Financial Services                 501 non-null    uint8
 21  Forest Materials                   501 non-null    uint8
 22  Healthcare                         501 non-null    uint8
 23  Information Technology             501 non-null    uint8
 24  Media Entertainment & Publication  501 non-null    uint8
 25  Metals & Mining                    501 non-null    uint8
 26  Oil Gas & Consumable Fuels         501 non-null    uint8
 27  Power                              501 non-null    uint8
 28  Realty                             501 non-null    uint8
 29  Services                           501 non-null    uint8
 30  Telecommunication                  501 non-null    uint8
 31  Textiles                           501 non-null    uint8
 32  Target                             500 non-null    float64
dtypes: float64(9), int64(1), object(2), uint8(21)
memory usage: 57.4+ KB

In [283]:
df=df.drop('365 Day Percentage Change',axis=1)

In [284]:
df

,Open,High,Low,Previous Close,Last Traded Price,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,30 Day Percentage Change,...,Information Technology,Media Entertainment & Publication,Metals & Mining,Oil Gas & Consumable Fuels,Power,Realty,Services,Telecommunication,Textiles,Target
0,21950.00,21999.00,21126.05,21854.05,21575.00,4159,8.965357e+07,27800.00,17273.00,8.22,...,0,0,0,0,0,0,0,0,0,400.50
1,400.50,401.80,394.10,403.85,400.00,31782,1.262731e+07,749.75,378.00,-5.10,...,0,0,0,0,0,0,0,0,0,1997.10
2,1997.10,2004.05,1894.50,2015.45,1943.15,150704,2.907728e+08,3340.00,1815.00,-9.39,...,0,0,0,0,0,0,0,0,0,2260.35
3,2260.35,2311.50,2260.35,2300.90,2280.00,97053,2.210935e+08,2487.85,1618.05,-5.21,...,0,0,0,0,0,0,0,0,0,18700.40
4,18700.40,19200.00,18605.00,18760.40,19199.80,12396,2.346770e+08,23934.45,15514.00,5.84,...,0,0,0,0,0,0,0,0,0,89.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,273.15,273.55,268.40,272.10,270.00,186578,5.046748e+07,587.00,246.65,-11.02,...,1,0,0,0,0,0,0,0,0,7748.00
497,7748.00,7900.00,7525.30,7716.60,7680.00,12790,9.884624e+07,8780.05,6793.30,1.43,...,0,0,0,0,0,0,0,0,0,54.15
498,54.15,56.70,52.55,53.85,56.00,112078641,6.193466e+09,169.00,50.05,-27.86,...,0,0,0,0,0,0,0,0,0,356.90
499,356.90,364.05,354.30,357.00,364.00,862373,3.100145e+08,651.90,319.00,-5.64,...,0,0,0,0,0,0,0,0,0,1635.00
500,1635.00,1635.00,1605.00,1636.85,1627.00,10803,1.749567e+07,2476.85,1430.00,6.25,...,0,0,0,0,0,0,0,0,0,NaN

In [285]:
df=df.drop('30 Day Percentage Change',axis=1)

In [286]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Open                               501 non-null    float64
 1   High                               501 non-null    float64
 2   Low                                501 non-null    float64
 3   Previous Close                     501 non-null    float64
 4   Last Traded Price                  501 non-null    float64
 5   Share Volume                       501 non-null    int64
 6   Value (Indian Rupee)               501 non-null    float64
 7   52 Week High                       501 non-null    float64
 8   52 Week Low                        501 non-null    float64
 9   Automobile and Auto Components     501 non-null    uint8
 10  Capital Goods                      501 non-null    uint8
 11  Chemicals                          501 non-null    uint8
 12  Construction                       501 non-null    uint8
 13  Construction Materials             501 non-null    uint8
 14  Consumer Durables                  501 non-null    uint8
 15  Consumer Services                  501 non-null    uint8
 16  Diversified                        501 non-null    uint8
 17  Fast Moving Consumer Goods         501 non-null    uint8
 18  Financial Services                 501 non-null    uint8
 19  Forest Materials                   501 non-null    uint8
 20  Healthcare                         501 non-null    uint8
 21  Information Technology             501 non-null    uint8
 22  Media Entertainment & Publication  501 non-null    uint8
 23  Metals & Mining                    501 non-null    uint8
 24  Oil Gas & Consumable Fuels         501 non-null    uint8
 25  Power                              501 non-null    uint8
 26  Realty                             501 non-null    uint8
 27  Services                           501 non-null    uint8
 28  Telecommunication                  501 non-null    uint8
 29  Textiles                           501 non-null    uint8
 30  Target                             500 non-null    float64
dtypes: float64(9), int64(1), uint8(21)
memory usage: 49.5 KB

In [287]:
scaler=StandardScaler()

In [288]:
df

,Open,High,Low,Previous Close,Last Traded Price,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,Automobile and Auto Components,...,Information Technology,Media Entertainment & Publication,Metals & Mining,Oil Gas & Consumable Fuels,Power,Realty,Services,Telecommunication,Textiles,Target
0,21950.00,21999.00,21126.05,21854.05,21575.00,4159,8.965357e+07,27800.00,17273.00,0,...,0,0,0,0,0,0,0,0,0,400.50
1,400.50,401.80,394.10,403.85,400.00,31782,1.262731e+07,749.75,378.00,0,...,0,0,0,0,0,0,0,0,0,1997.10
2,1997.10,2004.05,1894.50,2015.45,1943.15,150704,2.907728e+08,3340.00,1815.00,0,...,0,0,0,0,0,0,0,0,0,2260.35
3,2260.35,2311.50,2260.35,2300.90,2280.00,97053,2.210935e+08,2487.85,1618.05,0,...,0,0,0,0,0,0,0,0,0,18700.40
4,18700.40,19200.00,18605.00,18760.40,19199.80,12396,2.346770e+08,23934.45,15514.00,0,...,0,0,0,0,0,0,0,0,0,89.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,273.15,273.55,268.40,272.10,270.00,186578,5.046748e+07,587.00,246.65,0,...,1,0,0,0,0,0,0,0,0,7748.00
497,7748.00,7900.00,7525.30,7716.60,7680.00,12790,9.884624e+07,8780.05,6793.30,1,...,0,0,0,0,0,0,0,0,0,54.15
498,54.15,56.70,52.55,53.85,56.00,112078641,6.193466e+09,169.00,50.05,0,...,0,0,0,0,0,0,0,0,0,356.90
499,356.90,364.05,354.30,357.00,364.00,862373,3.100145e+08,651.90,319.00,0,...,0,0,0,0,0,0,0,0,0,1635.00
500,1635.00,1635.00,1605.00,1636.85,1627.00,10803,1.749567e+07,2476.85,1430.00,0,...,0,0,0,0,0,0,0,0,0,NaN

In [289]:
df.isna().sum()

Open                                 0
High                                 0
Low                                  0
Previous Close                       0
Last Traded Price                    0
Share Volume                         0
Value (Indian Rupee)                 0
52 Week High                         0
52 Week Low                          0
Automobile and Auto Components       0
Capital Goods                        0
Chemicals                            0
Construction                         0
Construction Materials               0
Consumer Durables                    0
Consumer Services                    0
Diversified                          0
Fast Moving Consumer Goods           0
Financial Services                   0
Forest Materials                     0
Healthcare                           0
Information Technology               0
Media Entertainment & Publication    0
Metals & Mining                      0
Oil Gas & Consumable Fuels           0
Power                                0
Realty                               0
Services                             0
Telecommunication                    0
Textiles                             0
Target                               1
dtype: int64

In [290]:
df=df.dropna(axis=0)

In [291]:
y=df['Target']
x=df.drop('Target',axis=1)

In [292]:
y

0        400.50
1       1997.10
2       2260.35
3      18700.40
4         89.00
         ...
495      273.15
496     7748.00
497       54.15
498      356.90
499     1635.00
Name: Target, Length: 500, dtype: float64

In [294]:
scaler=StandardScaler()
x=pd.DataFrame(scaler.fit_transform(x),columns=x.columns,index=x.index)

In [295]:
x

,Open,High,Low,Previous Close,Last Traded Price,Share Volume,Value (Indian Rupee),52 Week High,52 Week Low,Automobile and Auto Components,...,Healthcare,Information Technology,Media Entertainment & Publication,Metals & Mining,Oil Gas & Consumable Fuels,Power,Realty,Services,Telecommunication,Textiles
0,4.572651,4.467587,4.423910,4.539930,4.421501,-0.274425,-0.178872,4.471694,4.153115,-0.238919,...,-0.340693,-0.248135,-0.135388,-0.169725,-0.187608,-0.149983,-0.149983,-0.209383,-0.142857,-0.142857
1,-0.251910,-0.251693,-0.250196,-0.251048,-0.250826,-0.271489,-0.196637,-0.250011,-0.234600,-0.238919,...,2.935198,-0.248135,-0.135388,-0.169725,-0.187608,-0.149983,-0.149983,-0.209383,-0.142857,-0.142857
2,0.105541,0.098420,0.088076,0.108909,0.089674,-0.258846,-0.132486,0.202125,0.138596,-0.238919,...,-0.340693,-0.248135,-0.135388,-0.169725,-0.187608,-0.149983,-0.149983,-0.209383,-0.142857,-0.142857
3,0.164479,0.165602,0.170558,0.172665,0.164001,-0.264549,-0.148557,0.053379,0.087447,-0.238919,...,-0.340693,-0.248135,-0.135388,-0.169725,-0.187608,-0.149983,-0.149983,-0.209383,-0.142857,-0.142857
4,3.845122,3.855967,3.855529,3.848953,3.897406,-0.273549,-0.145424,3.796950,3.696294,-0.238919,...,2.935198,-0.248135,-0.135388,-0.169725,-0.187608,-0.149983,-0.149983,-0.209383,-0.142857,-0.142857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,-0.293888,-0.292326,-0.291567,-0.293429,-0.291537,0.164345,0.003598,-0.314779,-0.289450,-0.238919,...,-0.340693,-0.248135,7.386173,-0.169725,-0.187608,-0.149983,-0.149983,-0.209383,-0.142857,-0.142857
496,-0.280421,-0.279718,-0.278535,-0.280475,-0.279511,-0.255032,-0.187909,-0.278420,-0.268712,-0.238919,...,-0.340693,4.030059,-0.135388,-0.169725,-0.187608,-0.149983,-0.149983,-0.209383,-0.142857,-0.142857
497,1.393068,1.386765,1.357564,1.382281,1.355528,-0.273508,-0.176751,1.151703,1.431485,4.185513,...,-0.340693,-0.248135,-0.135388,-0.169725,-0.187608,-0.149983,-0.149983,-0.209383,-0.142857,-0.142857
498,-0.329452,-0.327102,-0.327200,-0.329222,-0.326731,11.640384,1.228897,-0.351383,-0.319770,-0.238919,...,-0.340693,-0.248135,-0.135388,-0.169725,-0.187608,-0.149983,-0.149983,-0.209383,-0.142857,-0.142857
499,-0.261671,-0.259942,-0.259169,-0.261512,-0.258770,-0.183187,-0.128048,-0.267091,-0.249922,-0.238919,...,2.935198,-0.248135,-0.135388,-0.169725,-0.187608,-0.149983,-0.149983,-0.209383,-0.142857,-0.142857

In [298]:
#splitting the dataset into x and y
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=1)

In [299]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(350, 30)
(150, 30)
(350,)
(150,)

In [302]:
from sklearn.linear_model import LinearRegression

In [303]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [304]:
model.score(x_test,y_test)

-0.06137843373285934

In [306]:
model.evaluate(x_train)

AttributeError: 'LinearRegression' object has no attribute 'evaluate'