In [50]:
#importing library
import numpy as np
import pandas as pd
pd.set_option('max.columns',None)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

In [51]:
df=pd.read_json('../input/netherlands-rent-properties/properties.json',lines=True)
df

,_id,externalId,areaRaw,areaSqm,city,coverImageUrl,crawlStatus,crawledAt,datesPublished,firstSeenAt,furnish,lastSeenAt,latitude,longitude,postalCode,postedAgo,propertyType,rawAvailability,rent,rentDetail,rentRaw,source,title,url,additionalCosts,additionalCostsRaw,deposit,depositRaw,descriptionNonTranslated,descriptionNonTranslatedRaw,descriptionTranslated,descriptionTranslatedRaw,detailsCrawledAt,energyLabel,gender,internet,isRoomActive,kitchen,living,matchAge,matchAgeBackup,matchCapacity,matchGender,matchGenderBackup,matchLanguages,matchStatus,matchStatusBackup,pageDescription,pageTitle,pets,registrationCost,registrationCostRaw,roommates,shower,smokingInside,toilet,userDisplayName,userId,userLastLoggedOn,userMemberSince,userPhotoUrl,additionalCostsDescription
0,{'$oid': '5d2b113a43cbfd7c77a998f4'},room-1686123,14 m2,14,Rotterdam,https://resources.kamernet.nl/image/913b4b03-5...,done,{'$date': '2019-07-26T22:18:23.018+0000'},"[{'$date': '2019-07-14T11:25:46.511+0000'}, {'...",{'$date': '2019-07-14T11:25:46.511+0000'},Unfurnished,{'$date': '2019-07-26T22:18:23.142+0000'},51.896601,4.514993,3074HN,4w,Room,26-06-'19 - Indefinite period,500,,"€ 500,-",kamernet,West-Varkenoordseweg,https://kamernet.nl/en/for-rent/room-rotterdam...,50.0,\n € 50\n ...,500.0,\n € 500\n ...,"Nice room for rent, accros the Feyenoord stadi...","\nNice room for rent, accros the Feyenoord sta...","Nice room for rent, accros the Feyenoord stadi...","\nNice room for rent, accros the Feyenoord sta...",{'$date': '2019-07-22T07:10:41.849+0000'},Unknown,Mixed,Yes,true,Shared,None,16 years -\n 99 years,16 years -\n 99 years,1 person,Not important,Not important,Not important,Not important,Not important,"Room for rent in Rotterdam, West-Varkenoordse...",Room for rent in Rotterdam €500 | Kamernet,No,0,\n € 0\n ...,5,Shared,No,Shared,Huize west,4680711.0,21-07-2019,26-06-2019,https://resources.kamernet.nl/Content/images/s...,NaN
1,{'$oid': '5d2b113a43cbfd7c77a9991a'},studio-1691193,30 m2,30,Amsterdam,https://resources.kamernet.nl/image/5e11d6b5-8...,done,{'$date': '2019-08-10T22:28:46.099+0000'},"[{'$date': '2019-07-14T11:25:46.677+0000'}, {'...",{'$date': '2019-07-14T11:25:46.677+0000'},Furnished,{'$date': '2019-08-10T22:28:46.229+0000'},52.370200,4.920721,1018AS,4w,Studio,15-08-'19 - Indefinite period,950,Utilities incl.,"€ 950,- Utilities incl.",kamernet,Parelstraat,https://kamernet.nl/en/for-rent/studio-amsterd...,0.0,\n € 0\n ...,895.0,\n € 895\n ...,"Efficiently furnished, with a large balcony, a...","\nEfficiently furnished, with a large balcony,...","Efficiently furnished, with a large balcony, a...","\nEfficiently furnished, with a large balcony,...",{'$date': '2019-07-22T06:29:33.112+0000'},Unknown,Unknown,Yes,true,Own,Own,18 years -\n 99 years,18 years -\n 99 years,1 person,Not important,Not important,Not important,"Working student, Working","Working student, Working","Studio for rent in Amsterdam, Parelstraat, fo...",Studio for rent in Amsterdam €950 | Kamernet,No,0,\n € 0\n ...,None,Own,No,Own,Cor,1865530.0,20-07-2019,05-01-2012,https://resources.kamernet.nl/Content/images/p...,NaN
2,{'$oid': '5d2b113a43cbfd7c77a99931'},room-1690545,11 m2,11,Amsterdam,https://resources.kamernet.nl/image/74b93a27-a...,done,{'$date': '2019-10-02T22:00:33.141+0000'},"[{'$date': '2019-07-14T11:25:46.834+0000'}, {'...",{'$date': '2019-07-14T11:25:46.834+0000'},Furnished,{'$date': '2019-10-02T22:00:33.264+0000'},52.350880,4.854786,1075SB,09 Jul,Room,01-08-'19 - Indefinite period,1000,Utilities incl.,"€ 1000,- Utilities incl.",kamernet,Zeilstraat,https://kamernet.nl/en/for-rent/room-amsterdam...,NaN,\n -\n ...,1000.0,\n € 1000\n ...,Kamer van 11m2 vlakbij het Vondelpark. Met een...,\nKamer van 11m2 vlakbij het Vondelpark. Met e...,Kamer van 11m2 vlakbij het Vondelpark. Met een...,\nKamer van 11m2 vlakbij het Vondelpark. Met e...,{'$date': '2019-07-21T08:44:32.816+0000'},Unknown,Mixed,Yes,true,Shared,Shared,16 years -\n 93 years,16 years -\n 93 years,1 person,Not important,Not important,Not important,Not important,Not important,"Room for rent in Amsterdam, Zeilstraat, for €...",Room for rent in Amsterdam €1000 | Kamernet,Yes,None,\n -\n ...,1,Shared,Yes,Shared,Felix,4466569.0,20-07-2019,05-07-2018,https://resources.kamernet.nl/Content/images/p...,NaN
3,{'$oid': '5d2b113a43cbfd7c77a9994a'},room-1680036,16 m2,16,Assen,https://resources.kamernet.nl/image/84e95365-6...,done,{'$date': '2019-07-18T22:00:31.018+0000'},"[{'$date': '2019-07-14T11:25:46.988+0000'}, {'...",{'$date': '2019-07-14T11:25:46.988+0000'},Unfurnished,{'$date': '2019-07-18T22:00:31.174+0000'},53.013494,6.561012,9407BG,17 Jun,Room,16-06-'19 - Indefinite period,290,Utilities incl.,"€ 290,- Utilities incl.",kamernet,Ruiterakker,https://kamernet.nl/en/for-rent/room-assen/rui...,NaN,-,290.0,€ 290,De kamer is 16m2De kamer is voorzien van een z...,De kamer is 16m2<br><br>De kamer is voorzien ...,De kamer is 16m2De kamer is voorzien van een z...,De kamer is 16m2<br><br>De kamer is voorzien ...,{'$date': '2019-07-27T19:03:44.443+0000'},Unknown,Female,Yes,false,Shared,None,18 years - 32 years,18 years - 32 years,1 person,Female,Female,Not important,"Student, Working student","Student, Working student","Room for rent in Assen, Ruiterakker, for €290...",Room for rent in Assen €290 | Kamernet,No,None,-,4,Shared,Yes,Shared,Albert,783341.0,26-07-2019,09-11-2006,https://resources.kamernet.nl/Content/images/p...,NaN
4,{'$oid': '5d2b113b43cbfd7c77a9997c'},room-1691356,22 m2,22,Rotterdam,https://resources.kamernet.nl/Content/images/p...,done,{'$date': '2019-08-12T02:06:14.635+0000'},"[{'$date': '2019-07-14T11:25:47.193+0000'}, {'...",{'$date': '2019-07-14T11:25:47.193+0000'},Unfurnished,{'$date': '2019-08-12T02:06:14.755+0000'},51.932871,4.479732,3035AK,4w,Room,01-08-'19 - Indefinite period,475,Utilities incl.,"€ 475,- Utilities incl.",kamernet,Zwart Janstraat,https://kamernet.nl/en/for-rent/room-rotterdam...,NaN,\n -\n ...,500.0,\n € 500\n ...,"gedeeltelijk gemeubileerd,met een kitchenette ...","\ngedeeltelijk gemeubileerd,met een kitchenett...",,\n,{'$date': '2019-07-21T08:13:53.217+0000'},Unknown,Male,Unknown,true,Own,Own,16 years -\n 99 years,16 years -\n 99 years,1 person,Male,Male,Not important,"Student, Working student, Working","Student, Working student, Working","Room for rent in Rotterdam, Zwart Janstraat, ...",Room for rent in Rotterdam €475 | Kamernet,No,None,\n -\n ...,1,Shared,No,Shared,John,3338401.0,19-07-2019,24-08-2014,https://resources.kamernet.nl/image/3177baf7-5...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46717,{'$oid': '5e5dada77fc8c93d83042924'},room-1774711,28 m2,28,Rotterdam,https://resources.kamernet.nl/image/198697b0-6...,done,{'$date': '2020-03-03T01:06:47.516+0000'},[{'$date': '2020-03-03T01:06:47.640+0000'}],{'$date': '2020-03-03T01:06:47.640+0000'},Furnished,{'$date': '2020-03-03T01:06:47.640+0000'},51.928624,4.507187,3061AG,2d,Room,01-03-'20 - Indefinite period,800,,"€ 800,-",kamernet,Oudedijk,https://kamernet.nl/en/for-rent/room-rotterdam...,200.0,€ 200,1000.0,€ 1000,"Recent available, completely furnished room in...","Recent available, completely furnished room i...","Recent available, completely furnished room in...","Recent available, completely furnished room i...",{'$date': '2020-03-03T09:32:18.481+0000'},Unknown,Unknown,Yes,true,Shared,Shared,16 years - 99 years,16 years - 99 years,> 5 persons,Not important,Not important,Not important,Not important,Not important,"Room for rent in Rotterdam, Oudedijk, for €80...",Room for rent in Rotterdam €800 | Kamernet,No,None,NA,Unknown,Shared,No,Shared,Xandra,4490595.0,03-03-2020,08-08-2018,https://resources.kamernet.nl/image/1317498e-a...,NaN
46718,{'$oid': '5e5daddf7fc8c93d83043cfd'},room-1774600,16 m2,16,Harmelen,https://resources.kamernet.nl/image/8d75725a-d...,done,{'$date': '2020-03-03T01:07:43.775+0000'},[{'$date': '2020-03-03T01:07:43.898+0000'}],{'$date': '2020-03-03T01:07:43.898+0000'},Furnished,{'$date': '2020-03-03T01:07:43.898+0000'},52.086568,4.959942,3481VE,3d,Room,08-02-'20 - Indefinite period,400,Utilities incl.,"€ 400,- Utilities incl.",kamernet,Wilhelminalaan,https://kamernet.nl/en/for-rent/room-harmelen/...,NaN,NA,NaN,-,Gerenoveerde zolderkamer te huur per direct.De...,Gerenoveerde zolderkamer te huur per direct.<...,,,{'$date': '2020-03-03T08:30:24.981+0000'},Unknown,Male,Yes,true,Shared,Shared,16 years - 99 years,16 years - 99 years,1 person,Not important,Not important,Not important,Student,Student,"Room for rent in Harmelen, Wilhelminalaan, fo...",Room for rent in Harmelen €400 | Kamernet,No,None,NA,2,Shared,No,Shared,Michel,4356840.0,24-02-2020,06-12-2017,https://resources.kamernet.nl/image/336ab03e-f...,NA
46719,{'$oid': '5e5dade07fc8c93d83043d2d'},room-1774595,30 m2,30,Rotterdam,https://resources.kamernet.nl/image/481fb7dd-a...,done,{'$date': '2020-03-03T01:07:43.947+0000'},[{'$date': '2020-03-03T01:07:44.071+0000'}],{'$date': '2020-03-03T01:07:44.071+0000'},Furnished,{'$date': '2020-03-03T01:07:44.071+0000'},51.928624,4.507187,3061AG,3d,Room,01-03-'20 - Indefinite period,950,,"€ 950,-",kamernet,Oudedijk,https://kamernet.nl/en/for-rent/room-rotterdam...,300.0,€ 300,1250.0,€ 1250,"Beautiful, new furnished room/apartment in 5 m...","Beautiful, new furnished room/apartment in 5 ...","Beautiful, new furnished room/apartment in 5 m...","Beautiful, new furnished room/apartment in 5 ...",{'$date': '2020-03-03T02:35:17.266+0000'},Unknown,Unknown,Yes,true,Shared,Shared,16 years - 99 years,16 years - 99 years,> 5 persons,Not important,Not important,Not important,"Student, Working student, Working","Student, Working student, Working","Room for rent in Rotterdam, Oudedijk, for €95...",Room for rent in Rotterdam €950 | Kamernet,No,None,NA,Unknown,Shared,No,Shared,Xandra,4490595.0,02-03-2020,08-08-2018,https://resources.kamernet.nl/image/1317498e-a...,NaN
46720,{'$oid': '5e5dade27fc8c93d83043e7b'},room-1774582,35 m2,35,Rotterdam,https://resources.kamernet.nl/image/809ca8b1-c...,done,{'$date': '2020-03-03T01:07:45.950+0000'},[{'$date': '2020-03-03T01:07:46.072+0000'}],{'$date': '2020-03-03T01:07:46.072+0000'},Furnished,{'$date': '2020-03-03T01:07:46.072+0000'},51.928624,4.507187,3061AG,3d,Room,01-03-'20 - Indefinite period,1050,Utilities incl.,"€ 1050,- Utilities incl.",kamernet,Oudedijk,https://kamernet.nl/en/for-rent/room-rotterdam...,300.0,€ 300,1350.0,€ 1350,"Large, completely furnished room in 5 minutes ...","Large, completely furnished room in 5 minutes...","Large, completely furnished room in 5 minutes ...","Large, completely furnished room in 5 minutes...",{'$date': '2020-03-03T06:31:13.654+0000'},Unknown,Unknown,Yes,true,Shared,Shared,16 years - 99 years,16 years - 99 years,1 person,Not important,Not important,Not important,"Student, Working student, Working","Student, Working student, Working","Room for rent in Rotterdam, Oudedijk, for €10...",Room for rent in Rotterdam €1050 | Kamernet,No,None,NA,6,Shared,No,Shared,Xandra,4490595.0,03-03-2020,08-08-2018,https://resources.kamernet.nl/image/1317498e-a...,NaN
46721,{'$oid': '5e5db1ad7fc8c93d8305b134'},studio-1765323,25 m2,25,Rotterdam,https://resources.kamernet.nl/image/203d5d86-9...,done,{'$date': '2020-03-03T01:23:57.716+0000'},[{'$date': '2020-03-03T01:23:57.836+0000'}],{'$date': '2020-03-03T01:23:57.836+0000'},Furnished,{'$date': '2020-03-03T01:23:57.836+0000'},51.921077,4.463528,3014CD,2w,Studio,01-05-'20 - Indefinite period,738,Utilities incl.,"€ 738,- Utilities incl.",kamernet,Henegouwerlaan,https://kamernet.nl/en/for-rent/studio-rotterd...,NaN,NA,NaN,-,Private room in apartment available from now!T...,Private room in apartment available from now!...,Private room in apartment available from now!T...,Private room in apartment available from now!...,{'$date': '2020-03-03T07:32:19.351+0000'},Unknown,None,Yes,true,Shared,Own,18 years - 99 years,18 years - 99 years,1 person,Female,Female,Not important,"Student, Working student, Working","Student, Working student, Working","Studio for rent in Rotterdam, Henegouwerlaan,...",Studio for rent in Rotterdam €738 | Kamernet,No,None,NA,None,Shared,No,Shared,Geert-Jan,4756677.0,02-03-2020,13-10-2019,https://resources.kamernet.nl/image/c609148f-e...,NA

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46722 entries, 0 to 46721
Data columns (total 62 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   _id                          46722 non-null  object
 1   externalId                   46722 non-null  object
 2   areaRaw                      46722 non-null  object
 3   areaSqm                      46722 non-null  int64
 4   city                         46722 non-null  object
 5   coverImageUrl                46722 non-null  object
 6   crawlStatus                  46722 non-null  object
 7   crawledAt                    46722 non-null  object
 8   datesPublished               46722 non-null  object
 9   firstSeenAt                  46722 non-null  object
 10  furnish                      46722 non-null  object
 11  lastSeenAt                   46722 non-null  object
 12  latitude                     46722 non-null  float64
 13  longitude                    46722 non-null  float64
 14  postalCode                   46722 non-null  object
 15  postedAgo                    46722 non-null  object
 16  propertyType                 46722 non-null  object
 17  rawAvailability              46722 non-null  object
 18  rent                         46722 non-null  int64
 19  rentDetail                   46722 non-null  object
 20  rentRaw                      46722 non-null  object
 21  source                       46722 non-null  object
 22  title                        46722 non-null  object
 23  url                          46722 non-null  object
 24  additionalCosts              14301 non-null  float64
 25  additionalCostsRaw           46622 non-null  object
 26  deposit                      27704 non-null  float64
 27  depositRaw                   46622 non-null  object
 28  descriptionNonTranslated     46622 non-null  object
 29  descriptionNonTranslatedRaw  46622 non-null  object
 30  descriptionTranslated        46622 non-null  object
 31  descriptionTranslatedRaw     46622 non-null  object
 32  detailsCrawledAt             46722 non-null  object
 33  energyLabel                  46622 non-null  object
 34  gender                       45810 non-null  object
 35  internet                     46622 non-null  object
 36  isRoomActive                 46622 non-null  object
 37  kitchen                      46622 non-null  object
 38  living                       46622 non-null  object
 39  matchAge                     46622 non-null  object
 40  matchAgeBackup               46622 non-null  object
 41  matchCapacity                46622 non-null  object
 42  matchGender                  46622 non-null  object
 43  matchGenderBackup            46622 non-null  object
 44  matchLanguages               46622 non-null  object
 45  matchStatus                  46622 non-null  object
 46  matchStatusBackup            46622 non-null  object
 47  pageDescription              46622 non-null  object
 48  pageTitle                    46622 non-null  object
 49  pets                         46622 non-null  object
 50  registrationCost             4688 non-null   object
 51  registrationCostRaw          46622 non-null  object
 52  roommates                    45810 non-null  object
 53  shower                       46622 non-null  object
 54  smokingInside                46622 non-null  object
 55  toilet                       46622 non-null  object
 56  userDisplayName              46622 non-null  object
 57  userId                       46622 non-null  float64
 58  userLastLoggedOn             46622 non-null  object
 59  userMemberSince              46622 non-null  object
 60  userPhotoUrl                 46622 non-null  object
 61  additionalCostsDescription   20546 non-null  object
dtypes: float64(5), int64(2), object(55)
memory usage: 22.1+ MB

In [53]:
def preproces_inputs(df):
    df=df.copy()
    bad_rows=df.query("crawlStatus=='unavailable'").index
    df=df.drop(bad_rows,axis=0).reset_index(drop=True)
    #getting features with selected columns
    df=df[['areaSqm','city','furnish','latitude','longitude',
          'propertyType','rent','internet','kitchen','living',
          'pets','shower','smokingInside','toilet']]
    df=df.replace({"":np.NaN,"Unknown":np.NaN})
    missing_value_columns=df.columns[df.isna().sum()>0]
    for column in missing_value_columns:
        df[column]=df[column].fillna(df[column].mode()[0])
    #Split the data
    y=df['rent']
    x=df.drop('rent',axis=1)
    x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7)
    return x_train,x_test,y_train,y_test,x

In [54]:
x_train,x_test,y_train,y_test,x=preproces_inputs(df)

In [55]:
#checking for missing values
x.isna().mean()

areaSqm          0.0
city             0.0
furnish          0.0
latitude         0.0
longitude        0.0
propertyType     0.0
internet         0.0
kitchen          0.0
living           0.0
pets             0.0
shower           0.0
smokingInside    0.0
toilet           0.0
dtype: float64

In [56]:
x

,areaSqm,city,furnish,latitude,longitude,propertyType,internet,kitchen,living,pets,shower,smokingInside,toilet
0,14,Rotterdam,Unfurnished,51.896601,4.514993,Room,Yes,Shared,None,No,Shared,No,Shared
1,30,Amsterdam,Furnished,52.370200,4.920721,Studio,Yes,Own,Own,No,Own,No,Own
2,11,Amsterdam,Furnished,52.350880,4.854786,Room,Yes,Shared,Shared,Yes,Shared,Yes,Shared
3,16,Assen,Unfurnished,53.013494,6.561012,Room,Yes,Shared,None,No,Shared,Yes,Shared
4,22,Rotterdam,Unfurnished,51.932871,4.479732,Room,Yes,Own,Own,No,Shared,No,Shared
...,...,...,...,...,...,...,...,...,...,...,...,...,...
46617,28,Rotterdam,Furnished,51.928624,4.507187,Room,Yes,Shared,Shared,No,Shared,No,Shared
46618,16,Harmelen,Furnished,52.086568,4.959942,Room,Yes,Shared,Shared,No,Shared,No,Shared
46619,30,Rotterdam,Furnished,51.928624,4.507187,Room,Yes,Shared,Shared,No,Shared,No,Shared
46620,35,Rotterdam,Furnished,51.928624,4.507187,Room,Yes,Shared,Shared,No,Shared,No,Shared
46621,25,Rotterdam,Furnished,51.921077,4.463528,Studio,Yes,Shared,Own,No,Shared,No,Shared

In [57]:
x.describe()

            areaSqm      latitude     longitude
count  46622.000000  46622.000000  46622.000000
mean      31.636974     52.201675      5.315371
std       29.877284      0.517286      0.798836
min        6.000000     50.770041      3.410016
25%       14.000000     51.925374      4.712789
50%       20.000000     52.162522      5.083407
75%       40.000000     52.370420      5.896593
max      675.000000     53.434608      7.206637

In [58]:
{column:list(x[column].unique()) for column in x.select_dtypes('object').columns}

{'city': ['Rotterdam',
  'Amsterdam',
  'Assen',
  'Groningen',
  'Zeist',
  'Maastricht',
  'Callantsoog',
  'Alphen aan den Rijn',
  'Tilburg',
  'Enschede',
  'Leeuwarden',
  'Eindhoven',
  'Wageningen',
  'Diemen',
  'Utrecht',
  'Almere',
  'Alkmaar',
  'Harderwijk',
  'Hilversum',
  'Delft',
  'Den Bosch',
  'Stoutenburg',
  'Leiden',
  'Den Haag',
  'Boxtel',
  'Badhoevedorp',
  'Veenendaal',
  'Amstelveen',
  'Nijmegen',
  'Venlo',
  'Zwolle',
  'Ubbena',
  'Arnhem',
  'Leimuiden',
  'Riel',
  'Nieuwegein',
  'Haren Gn',
  'Uitgeest',
  'Beverwijk',
  'Ede',
  'Nijkerk',
  'Amersfoort',
  'Loosdrecht',
  'Apeldoorn',
  'Vaals',
  'Velp',
  'Vlaardingen',
  'Montfoort',
  'Heemstede',
  'Breda',
  'Purmerend',
  'Baarn',
  'Spijkenisse',
  'Deventer',
  'Hengelo',
  'Capelle aan den IJssel',
  'Bovenkarspel',
  'Weesp',
  'Harskamp',
  'Zeeland',
  'Waalre',
  'IJsselstein',
  'Pijnacker',
  'Sittard',
  'Putten',
  'Vlissingen',
  'Haarlem',
  'Rijswijk',
  'Zandvoort',
  'Zutphen',
  'Heerlen',
  'Breukeleveen',
  'Hoofddorp',
  'Hoensbroek',
  'Rosmalen',
  'Son en Breugel',
  'Etten-Leur',
  'Dordrecht',
  'Bergschenhoek',
  'Almelo',
  'Wijchen',
  'Zaandam',
  'Zoetermeer',
  'Gouda',
  'Oudorp',
  'Haule',
  'Uithoorn',
  'Oss',
  'Beuningen Gld',
  'Lelystad',
  'Houten',
  'Wenum Wiesel',
  'Warmenhuizen',
  'Hattem',
  'Schiedam',
  'Leerdam',
  'Hellevoetsluis',
  'Delden',
  'Veldhoven',
  'Best',
  'Leersum',
  'Twello',
  'Wassenaar',
  'De Bilt',
  'Oud-Beijerland',
  'Halfweg',
  'Vreeland',
  'Winterswijk',
  'Stadskanaal',
  'Heemskerk',
  'Ammerzoden',
  'Vries',
  'Voorburg',
  'Coevorden',
  'Wijk aan Zee',
  'Haelen',
  'Zaltbommel',
  'Bedum',
  'Werkhoven',
  'Sint Pancras',
  'Raamsdonksveer',
  'Hooghalen',
  'Moergestel',
  'Vinkeveen',
  'Beek (gem Ubbergen)',
  'Bunnik',
  'Cuijk',
  'Berg en Dal',
  'Barneveld',
  'Uden',
  'Keijenborg',
  'Roden',
  'Abcoude',
  'Wormerveer',
  'Katwijk',
  'Medemblik',
  'Valkenswaard',
  'Neerkant',
  'Wehl',
  'Weert',
  'Schermerhorn',
  'Gieten',
  'Geldrop',
  'Mierlo',
  'Roermond',
  'Bemmel',
  'Lisse',
  'Beneden-Leeuwen',
  'Berlicum',
  'Valkenburg',
  'Nuenen',
  'Leiderdorp',
  'Soest',
  'De Rijp',
  'Hattemerbroek',
  'Maassluis',
  'Maarssen',
  'Marsum',
  'Helmond',
  'Malden',
  'Cadier en Keer',
  'Hoorn',
  'Nieuwveen',
  'Slochteren',
  'Dongen',
  'Ouderkerk aan de Amstel',
  'Scherpenzeel',
  'Terneuzen',
  'Zoeterwoude',
  'Heeswijk-Dinther',
  'Sassenheim',
  'Voorschoten',
  'Oudehaske',
  'Peize',
  'Beilen',
  'Heesch',
  'Wierden',
  'Geleen',
  'Ommen',
  'IJmuiden',
  'Vijfhuizen',
  'Huizen',
  'Castricum',
  'Vrouwenparochie',
  'Emmen',
  'Doorn',
  'Hoevelaken',
  'Roelofarendsveen',
  'Zuidhorn',
  'Grou',
  'Zwaag',
  'Bussum',
  'Haaften',
  'Cromvoirt',
  'Zeddam',
  'Vught',
  'Budel',
  'Bunschoten-Spakenburg',
  'Venhorst',
  'Aalsmeer',
  'Smilde',
  'Nieuwe Pekela',
  'De Wilp',
  'Tolbert',
  'Termunterzijl',
  'Visvliet',
  'Elst',
  'Bennekom',
  'Leusden',
  'Lunteren',
  'Westervoort',
  'Doetinchem',
  'Oudenbosch',
  'Oudkarspel',
  'De Meern',
  'Exloo',
  'Voerendaal',
  'Dalfsen',
  'Hoogerheide',
  'Bilthoven',
  'Woerden',
  'Surhuizum',
  'Woubrugge',
  'Voorhout',
  'Eijsden',
  'Tegelen',
  'Sprang-Capelle',
  'Doorwerth',
  'Hoogeveen',
  'Eygelshoven',
  'Groenekan',
  'Dronten',
  'Nistelrode',
  'Duivendrecht',
  'Hoenderloo',
  'Meppel',
  'Noordwijk',
  'Roosendaal',
  'Olst',
  'Wateringen',
  'Dokkum',
  'Steenwijk',
  'Rijpwetering',
  'Hoogezand',
  'Den Helder',
  'Moordrecht',
  'Reusel',
  'Velsen-Noord',
  'Beekbergen',
  'Teuge',
  'Vianen',
  'Nieuwersluis',
  'Bentveld',
  'De Kwakel',
  'Barendrecht',
  'Kudelstaart',
  'Didam',
  'Baak',
  'Leuth',
  'Veendam',
  'Molenhoek',
  'Velserbroek',
  'Gronsveld',
  'Middenmeer',
  'Eerbeek',
  'Goirle',
  'Gaanderen',
  'Renkum',
  'Sliedrecht',
  'Oost West en Middelbeers',
  'Ewijk',
  'Geulle',
  'Puttershoek',
  'Belfeld',
  'Delfgauw',
  'Oosterbeek',
  'Lisserbroek',
  'Enkhuizen',
  'Mill',
  'Heumen',
  'Meerssen',
  'Nuland',
  'Loenen',
  'Huissen',
  'Heerenveen',
  'Dwingeloo',
  'Persingen',
  'Voorst',
  'Naarden',
  'Rheden',
  'Markelo',
  'Laren',
  'Rilland',
  'Groesbeek',
  'Zennewijnen',
  'Hasselt',
  'Vroomshoop',
  'Heino',
  'Elburg',
  'Nieuwleusen',
  'Hillegom',
  'Wijhe',
  'Oldenzaal',
  'Bunde',
  'Brunssum',
  'Venhuizen',
  "'s-Graveland",
  'Landgraaf',
  'Mander',
  'Oene',
  'Eersel',
  'Linden',
  'Veghel',
  'Buitenkaag',
  'Monnickendam',
  'Maarheeze',
  'Heel',
  'Kerkrade',
  'Oirschot',
  'Dieren',
  'Oisterwijk',
  'Haaksbergen',
  'Heeze',
  'Huisseling',
  'Kampen',
  'Harmelen',
  'Angerlo',
  'Goes',
  'Oostrum',
  'Oegstgeest',
  'Klazienaveen',
  'Baarlo (LB)',
  'Mijdrecht',
  'Ruinerwold',
  'Gemert',
  'Sappemeer',
  'Wagenberg',
  'Berkel-Enschot',
  'Staphorst',
  'Ermelo',
  'Leidschendam',
  'Nieuw-Vennep',
  'Deurne',
  'Werkendam',
  'Koog aan de Zaan',
  'Velp (NB)',
  'Wilnis',
  'Montfort',
  'Limmen',
  'Kerkdriel',
  'Assendelft',
  'Schoorl',
  'Oosterhout',
  'Foxhol',
  'Hoogvliet Rotterdam',
  'Rhenen',
  'Boxmeer',
  'Bavel',
  'Drempt',
  'Hummelo',
  'Zuiderwoude',
  'Kortenhoef',
  'Garderen',
  'Bemelen',
  'Rijsenhout',
  'Vaassen',
  'Lieshout',
  'Ulvenhout AC',
  'Rhenoy',
  'Waalwijk',
  'Nederweert',
  'Burgum',
  'Rijnsburg',
  'Katwijk NB',
  'Ridderkerk',
  'Groot-Ammers',
  'Winsum',
  'Wervershoof',
  'Nijensleek',
  'Zuidwolde',
  'Randwijk',
  'Klarenbeek',
  'Noordwijkerhout',
  'Zevenaar',
  'Hengevelde',
  'Appingedam',
  'Delfzijl',
  'Bergen (NH)',
  'Heerhugowaard',
  'Borger',
  'Wieringerwaard',
  'Odijk',
  'Koedijk',
  'Boksum',
  'Ingen',
  'Epse',
  'Voorthuizen',
  'Drachten',
  'Schijndel',
  'Soesterberg',
  'Culemborg',
  'Driebergen-Rijsenburg',
  'Heusden',
  'Zwijndrecht',
  'Ubbergen',
  'Rozenburg',
  'Wanneperveen',
  'Asten',
  'Epe',
  'Loenen aan de Vecht',
  'Schellinkhout',
  'Heerde',
  'Zevenbergen',
  'Eibergen',
  'Wolvega',
  'Opmeer',
  'Warmond',
  'Ressen',
  'Lathum',
  'Schipluiden',
  'Leende',
  'Hooge Zwaluwe',
  'Hoogland',
  'Goutum',
  'Wormer',
  'Zwanenburg',
  'Vlijmen',
  "'t Waar",
  'Bleskensgraaf ca',
  'Kockengen',
  'Ten Post',
  'Sint Odilienberg',
  'Musselkanaal',
  'de Lutte',
  'Waarland',
  'Albergen',
  'Budel-Dorplein',
  'Nunspeet',
  'Meerkerk',
  'Hoek van Holland',
  'Waddinxveen',
  'Eemnes',
  'Lage Zwaluwe',
  'Overloon',
  'Zeegse',
  'Loon op Zand',
  'Overveen',
  'Beinsdorp',
  'Deest',
  'Bosch en Duin',
  'Benthuizen',
  'Rijen',
  'Geffen',
  'Meteren',
  'Weurt',
  'Hardenberg',
  'Wapenveld',
  'Lith',
  'Zuidlaren',
  'Beuningen',
  'Maria Hoop',
  'Vleuten',
  'Wezep',
  'Tiendeveen',
  'Naaldwijk',
  'Boskoop',
  'Heteren',
  'Tiel',
  'Swifterbant',
  'Alblasserdam',
  'Merselo',
  'Vinkel',
  'Ambt Delden',
  'Sneek',
  'St. Willebrord',
  'Ankeveen',
  'Aalst',
  'Pernis Rotterdam',
  'Twijzel',
  'Stolwijk',
  'Herveld',
  'Haarsteeg',
  'Grave',
  'Brakel',
  'Bergen op Zoom',
  'Oost-Souburg',
  'Maren-Kessel',
  'Noordbroek',
  'Hem',
  'Mook',
  'Buitenpost',
  'Lopikerkapel',
  'Onstwedde',
  'Brantgum',
  'Tynaarlo',
  'Horn',
  'Tricht',
  'Stellendam',
  'Goedereede',
  'Egmond aan Zee',
  'Bad Nieuweschans',
  'Anloo',
  'Wamel',
  'Groenlo',
  'Wessem',
  'Edam',
  'Burgerbrug',
  'Raalte',
  'Heelsum',
  'Liempde',
  'Doesburg',
  'Koudekerk aan den Rijn',
  'Wittem',
  'Amerongen',
  'Sint Jansklooster',
  'Galder',
  'Wijk bij Duurstede',
  'Nijverdal',
  'Westzaan',
  'Middelburg',
  'Akkrum',
  'Plasmolen',
  'Lent',
  'Rijssen',
  'Heiloo',
  'Sint-Michielsgestel',
  'Leek',
  'Venray',
  'Simpelveld',
  'Gorinchem',
  'Maarn',
  'Nijeveen',
  'Schagen',
  'Mantinge',
  'Deursen-Dennenburg',
  'Dedemsvaart',
  'Bleiswijk',
  'Huis ter Heide',
  "'s-Gravenzande",
  'Melick',
  'Achterveld (UT)',
  'Woudenberg',
  'Hulshorst',
  'Woerdense Verlaat',
  'Hardinxveld-Giessendam',
  'Nootdorp',
  'Wesepe',
  'Berkel en Rodenrijs',
  'Gilze',
  'Hilvarenbeek',
  'Winssen',
  'Grootebroek',
  'Groet',
  'Heerewaarden',
  'Hazerswoude-Dorp',
  'Kamerik',
  'Gennep',
  'Kwintsheul',
  'Breukelen',
  'Sint Geertruid',
  'Warnsveld',
  'Kraggenburg',
  'Hooglanderveen',
  'Rheezerveen',
  'Wernhout',
  'Westerbroek',
  'Ysselsteyn',
  'Lochem',
  'Kolhorn',
  'Kesteren',
  'Colijnsplaat',
  'Bakel',
  'Nieuw-Balinge',
  'Made',
  'Aadorp',
  'Buggenum',
  'Krommenie',
  'Zaandijk',
  'Ameide',
  'Den Ilp',
  'Geldermalsen',
  'Nederhorst den Berg',
  'Egmond aan den Hoef',
  'Hendrik-Ido-Ambacht',
  'De Steeg',
  'Drongelen',
  'Kamperland',
  'Veeningen',
  'Sint-Oedenrode',
  'Zeewolde',
  'Ter Aar',
  'Den Ham (GR)',
  'Borne',
  'Etten',
  'Zwartsluis',
  'Drunen',
  'Landsmeer',
  'Stevensweert',
  'Herkenbosch',
  'Reeuwijk',
  'Hoogmade',
  'Hoeven',
  'Oud Gastel',
  'Kimswerd',
  'Lijnden',
  'Dorst',
  'Geeuwenbrug',
  'Garmerwolde',
  'Aduard',
  'Koudekerke',
  'Hall',
  'Langbroek',
  'Knegsel',
  'Berg en Terblijt',
  'Papendrecht',
  'Winterswijk Woold',
  'Lierop',
  'Nuth',
  'Blaricum',
  'Aarle-Rixtel',
  'Krimpen aan den IJssel',
  'Nieuwkuijk',
  'Axel',
  'Kropswolde',
  'Schalkwijk',
  'Westerland',
  'Vierhouten',
  'Duiven',
  'Tubbergen',
  'Schinveld',
  'Waardenburg',
  'Nieuwe Niedorp',
  'Oostvoorne',
  'Loenersloot',
  'Ospel',
  'Schalkhaar',
  'Gendt',
  'Margraten',
  'Kaatsheuvel',
  'Schin op Geul',
  'Hurdegaryp',
  'Vessem',
  'Eelde',
  'De Lier',
  'Jorwert',
  'Bergeijk',
  'Surhuisterveen',
  'Terborg',
  'Raamsdonk',
  'Marum',
  'Aldtsjerk',
  'Farmsum',
  'Vijlen',
  'Den Horn',
  "'t Goy",
  'Oudeschip',
  'Noordscheschut',
  'Zundert',
  'Barsingerhorn',
  'Oosthuizen',
  'Middenbeemster',
  'Cadzand',
  'Schaijk',
  'Zwammerdam',
  'Stiens',
  'Klundert',
  'Bocholtz',
  'Schoonhoven',
  "'t Harde",
  'Rijsbergen',
  'IJsselmuiden',
  'Aarlanderveen',
  'Biezenmortel',
  'Harkstede GN',
  'Wintelre',
  'Gulpen',
  'Boekel',
  'Berghem',
  'Oldehove',
  'Warffum',
  'Harlingen',
  'Avenhorn',
  'Purmerland',
  'Veenhuizen',
  'Winschoten',
  'Rhoon',
  'Oude Pekela',
  'Bitgummole',
  'Lopik',
  'Escharen',
  'Oude Meer',
  'Stein',
  'Deil',
  'Thesinge',
  'Prinsenbeek',
  'Franeker',
  'Herten',
  'Steensel',
  'Netersel',
  'Hoogkarspel',
  'Eethen',
  "'s-Heerenberg",
  'Austerlitz',
  'Nietap',
  'Otterlo',
  'Hedel',
  'Godlinze',
  'Elsloo',
  'Zierikzee',
  'Est',
  'Vasse',
  'Diessen',
  'Stieltjeskanaal',
  'Terheijden',
  'Broekhuizenvorst',
  'Bentelo',
  'Den Hoorn (ZH)',
  'Winkel',
  'Luyksgestel',
  'Born',
  'Geertruidenberg',
  'Blije',
  'Krimpen aan de Lek',
  'Liessel',
  'Genemuiden',
  'Rockanje',
  'Brielle',
  'amsterdam',
  'Kiel-Windeweer',
  'Rumpt',
  'Serooskerke',
  'Beek (LB)',
  'Kloosterburen',
  'Rekken',
  'Berltsum',
  'Benschop',
  'Elst Ut'],
 'furnish': ['Unfurnished', 'Furnished', 'Uncarpeted'],
 'propertyType': ['Room',
  'Studio',
  'Apartment',
  'Anti-squat',
  'Student residence'],
 'internet': ['Yes', 'No'],
 'kitchen': ['Shared', 'Own', 'None'],
 'living': ['None', 'Own', 'Shared'],
 'pets': ['No', 'Yes', 'By mutual agreement'],
 'shower': ['Shared', 'Own', 'None'],
 'smokingInside': ['No', 'Yes', 'Not important'],
 'toilet': ['Shared', 'Own', 'None']}

In [59]:
x_train

,areaSqm,city,furnish,latitude,longitude,propertyType,internet,kitchen,living,pets,shower,smokingInside,toilet
10449,17,Groningen,Furnished,53.229877,6.542754,Room,No,Shared,None,No,Shared,No,Shared
7743,73,Amsterdam,Uncarpeted,52.354312,4.827012,Apartment,Yes,Own,Own,No,Own,No,Own
21133,15,Eindhoven,Uncarpeted,51.441713,5.498789,Room,Yes,Shared,None,No,Shared,No,Shared
43430,16,Rotterdam,Unfurnished,51.934269,4.475425,Room,No,Shared,Shared,No,Shared,No,Shared
30718,12,Amsterdam,Furnished,52.350438,4.897223,Room,Yes,Shared,None,No,Shared,No,Shared
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31869,16,Rotterdam,Furnished,51.936516,4.426403,Room,Yes,Shared,None,No,Shared,No,Shared
17061,10,Utrecht,Furnished,52.109722,5.089137,Room,Yes,Own,Own,No,Shared,No,Shared
38915,12,Eindhoven,Uncarpeted,51.428703,5.462280,Room,Yes,Shared,None,No,Shared,No,Shared
25016,20,Groningen,Furnished,53.218554,6.562027,Studio,Yes,Shared,Own,No,Own,No,Own
22734,26,Arnhem,Unfurnished,51.989990,5.925735,Room,Yes,Shared,None,No,Shared,No,Shared

# Building Pipleline and Training

In [60]:
{column:len(x[column].unique()) for column in x.select_dtypes('object').columns}

{'city': 737,
 'furnish': 3,
 'propertyType': 5,
 'internet': 2,
 'kitchen': 3,
 'living': 3,
 'pets': 3,
 'shower': 3,
 'smokingInside': 3,
 'toilet': 3}

In [61]:
nominal_features=[
    'city',
    'furnish',
    'internet',
    'propertyType',
    'kitchen',
    'living',
    'pets',
    'shower',
    'smokingInside',
    'toilet'
]

binary_transformer=Pipeline(steps=[
    ('ordinal',OrdinalEncoder())
])
nominal_transformer=Pipeline(steps=[
    ('onehot',OneHotEncoder(sparse=False,handle_unknown='ignore'))
])





preprocessor=ColumnTransformer(transformers=[
    ('binary',binary_transformer,['internet']),
    ('nominal',nominal_transformer,nominal_features)
],remainder='passthrough')






model=Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('regressor',RandomForestRegressor())
])

In [62]:
model.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('binary',
                                                  Pipeline(steps=[('ordinal',
                                                                   OrdinalEncoder())]),
                                                  ['internet']),
                                                 ('nominal',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse=False))]),
                                                  ['city', 'furnish',
                                                   'internet', 'propertyType',
                                                   'kitchen', 'living', 'pets',
                                                   'shower', 'smokingInside',
                                                   'toilet'])])),
                ('regressor', RandomForestRegressor())])

In [64]:
model.score(x_test,y_test)

0.8452111456242801

In [66]:
y_pred=model.predict(x_test)

In [70]:
np.sqrt(np.mean((y_test-y_pred)**2))

163.6721644665694

In [74]:
y_test.describe()

count    13987.000000
mean       667.599771
std        416.026034
min          1.000000
25%        390.000000
50%        550.000000
75%        800.000000
max       5999.000000
Name: rent, dtype: float64