In [3]:
#importing library
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score,f1_score

In [5]:
#loading the dataset
df=pd.read_csv('/kaggle/input/patient-treatment-classification/data-ori.csv')
#loading the dataset
df

,HAEMATOCRIT,HAEMOGLOBINS,ERYTHROCYTE,LEUCOCYTE,THROMBOCYTE,MCH,MCHC,MCV,AGE,SEX,SOURCE
0,35.1,11.8,4.65,6.3,310,25.4,33.6,75.5,1,F,out
1,43.5,14.8,5.39,12.7,334,27.5,34.0,80.7,1,F,out
2,33.5,11.3,4.74,13.2,305,23.8,33.7,70.7,1,F,out
3,39.1,13.7,4.98,10.5,366,27.5,35.0,78.5,1,F,out
4,30.9,9.9,4.23,22.1,333,23.4,32.0,73.0,1,M,out
...,...,...,...,...,...,...,...,...,...,...,...
4407,32.8,10.4,3.49,8.1,72,29.8,31.7,94.0,92,F,in
4408,33.7,10.8,3.67,6.7,70,29.4,32.0,91.8,92,F,in
4409,33.2,11.2,3.47,7.2,235,32.3,33.7,95.7,93,F,out
4410,31.5,10.4,3.15,9.1,187,33.0,33.0,100.0,98,F,in
4411,33.5,10.9,3.44,5.8,275,31.7,32.5,97.4,99,F,out

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4412 entries, 0 to 4411
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HAEMATOCRIT   4412 non-null   float64
 1   HAEMOGLOBINS  4412 non-null   float64
 2   ERYTHROCYTE   4412 non-null   float64
 3   LEUCOCYTE     4412 non-null   float64
 4   THROMBOCYTE   4412 non-null   int64
 5   MCH           4412 non-null   float64
 6   MCHC          4412 non-null   float64
 7   MCV           4412 non-null   float64
 8   AGE           4412 non-null   int64
 9   SEX           4412 non-null   object
 10  SOURCE        4412 non-null   object
dtypes: float64(7), int64(2), object(2)
memory usage: 379.3+ KB

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
HAEMATOCRIT,4412.0,38.197688,5.974784,13.70,34.375,38.60,42.50,69.00
HAEMOGLOBINS,4412.0,12.741727,2.079903,3.80,11.400,12.90,14.20,18.90
ERYTHROCYTE,4412.0,4.541260,0.784091,1.48,4.040,4.57,5.05,7.86
LEUCOCYTE,4412.0,8.718608,5.049041,1.10,5.675,7.60,10.30,76.60
THROMBOCYTE,4412.0,257.524479,113.972365,8.00,188.000,256.00,321.00,1183.00
MCH,4412.0,28.234701,2.672639,14.90,27.200,28.70,29.80,40.80
MCHC,4412.0,33.343042,1.228664,26.00,32.700,33.40,34.10,39.00
MCV,4412.0,84.612942,6.859101,54.00,81.500,85.40,88.70,115.60
AGE,4412.0,46.626473,21.731218,1.00,29.000,47.00,64.00,99.00

In [16]:
def preprocess_inputs(df):
    df=df.copy()
    
    df['SEX']=df['SEX'].replace({"M":1,"F":0})
    
    y=df['SOURCE']
    x=df.drop('SOURCE',axis=1)
    
    
    x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=123,shuffle=True)
    scaler=StandardScaler()
    
    scaler.fit(x_train)
    x_train=pd.DataFrame(scaler.transform(x_train),columns=x_train.columns,index=x_train.index)
    x_test=pd.DataFrame(scaler.transform(x_test),columns=x_test.columns,index=x_test.index)
    
    
    return x_train,x_test,y_train,y_test

In [17]:
x_train,x_test,y_train,y_test=preprocess_inputs(df)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(3088, 10)
(1324, 10)
(3088,)
(1324,)

/tmp/ipykernel_36/3811374962.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['SEX']=df['SEX'].replace({"M":1,"F":0})

In [19]:
x_test

,HAEMATOCRIT,HAEMOGLOBINS,ERYTHROCYTE,LEUCOCYTE,THROMBOCYTE,MCH,MCHC,MCV,AGE,SEX
33,0.512114,0.138193,0.437235,1.202925,-0.693090,-0.593268,-1.401396,-0.020866,-2.086957,-1.042347
2840,-2.052997,-2.108568,-2.322258,0.092714,0.706079,0.892668,-0.913688,1.543963,0.520458,-1.042347
1713,0.062387,-0.100824,0.132037,0.092714,1.286866,-0.481822,-0.669834,-0.223714,-0.348680,-1.042347
2007,-1.503330,-1.343713,-1.800879,-0.385825,-1.432274,1.301301,0.549434,1.268669,-0.074216,0.959374
3245,-0.753785,-0.292038,-0.770838,1.566615,1.383664,0.966965,2.175126,0.138515,0.749178,0.959374
...,...,...,...,...,...,...,...,...,...,...
3835,0.845245,0.855245,0.551683,-0.347542,-0.376297,0.372591,0.224296,0.341363,1.160875,0.959374
3585,-1.120229,-1.104696,-0.567373,1.490049,-1.986662,-1.039048,-0.182127,-1.122041,0.977899,0.959374
2649,-0.170805,-0.005217,-0.300326,-1.170630,-1.414674,0.484036,0.712003,0.254428,0.383225,-1.042347
1866,-1.553300,-2.251979,0.271919,-0.309259,1.190069,-4.233811,-4.490209,-3.469284,-0.211448,-1.042347
4351,-0.870381,-0.770072,-1.533831,-0.136985,-0.569893,1.895675,0.305581,2.065572,1.847037,-1.042347

# Training the Model

In [21]:
Models={"Logistic Regression":LogisticRegression(),
       'MLP Classifier':MLPClassifier(),
        'Random Forest':RandomForestClassifier(),
       'Decision Tree':DecisionTreeClassifier(),
        'Gradient Boosting': GradientBoostingClassifier()}

In [23]:
for name,model in Models.items():
    model.fit(x_train,y_train)
    print(name)
    print('Model Trained')
    print(model.score(x_test,y_test))

Logistic Regression
Model Trained
0.7220543806646526

/opt/conda/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

MLP Classifier
Model Trained
0.7537764350453172
Random Forest
Model Trained
0.736404833836858
Decision Tree
Model Trained
0.6555891238670695
Gradient Boosting
Model Trained
0.736404833836858