In [1]:
#importing the librart
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import GradientBoostingRegressor

In [4]:
#loading the dataset
df=pd.read_csv('../input/house-prices-in-poland/Houses.csv',encoding='latin-1')

In [5]:
df

,Unnamed: 0,address,city,floor,id,latitude,longitude,price,rooms,sq,year
0,0,Podgórze Zab³ocie Stanis³awa Klimeckiego,Kraków,2.0,23918.0,50.049224,19.970379,749000.0,3.0,74.05,2021.0
1,1,Praga-Po³udnie Grochowska,Warszawa,3.0,17828.0,52.249775,21.106886,240548.0,1.0,24.38,2021.0
2,2,Krowodrza Czarnowiejska,Kraków,2.0,22784.0,50.066964,19.920025,427000.0,2.0,37.00,1970.0
3,3,Grunwald,Poznañ,2.0,4315.0,52.404212,16.882542,1290000.0,5.0,166.00,1935.0
4,4,Ochota Gotowy budynek. Stan deweloperski. Osta...,Warszawa,1.0,11770.0,52.212225,20.972630,996000.0,5.0,105.00,2020.0
...,...,...,...,...,...,...,...,...,...,...,...
23759,23759,Stare Miasto Naramowice,Poznañ,0.0,3976.0,52.449649,16.949408,543000.0,4.0,77.00,2020.0
23760,23760,W³ochy,Warszawa,4.0,10206.0,52.186109,20.948438,910000.0,3.0,71.00,2017.0
23761,23761,Nowe Miasto Malta ul. Katowicka,Poznañ,0.0,4952.0,52.397345,16.961939,430695.0,3.0,50.67,2022.0
23762,23762,Podgórze Duchackie Walerego S³awka,Kraków,6.0,24148.0,50.024231,19.959569,359000.0,2.0,38.86,2021.0
23763,23763,Ursynów,Warszawa,2.0,10889.0,52.141039,21.032321,604800.0,3.0,63.00,1978.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23764 entries, 0 to 23763
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  23764 non-null  int64
 1   address     23764 non-null  object
 2   city        23764 non-null  object
 3   floor       23764 non-null  float64
 4   id          23764 non-null  float64
 5   latitude    23764 non-null  float64
 6   longitude   23764 non-null  float64
 7   price       23764 non-null  float64
 8   rooms       23764 non-null  float64
 9   sq          23764 non-null  float64
 10  year        23764 non-null  float64
dtypes: float64(8), int64(1), object(2)
memory usage: 2.0+ MB

In [17]:
#Preprocessing 
def preprocess_inputs(df):
    #copying the dataset
    df=df.copy()
    #dropping the unnamed columns
    df=df.drop('Unnamed: 0',axis=1)
    #dropping the address and id column
    df=df.drop(['address','id'],axis=1)
    #returning the dataset
    y=df['price']
    x=df.drop('price',axis=1)
    x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=1)
    return x_train,x_test,y_train,y_test

In [18]:
x_train,x_test,y_train,y_test=preprocess_inputs(df)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(16634, 7)
(7130, 7)
(16634,)
(7130,)

# Building Pipeline

In [22]:
nominal_transformer=Pipeline(steps=[
    ('onehot',OneHotEncoder(sparse=False))
])

preprocessor=ColumnTransformer(transformers=[
    ('nominal',nominal_transformer,['city'])
],remainder='passthrough')
model=Pipeline(steps=[
    ('preprecessor',preprocessor),
    ('scaler',StandardScaler()),
    ('regressor',GradientBoostingRegressor())
])

# Training

In [23]:
model.fit(x_train,y_train)

Pipeline(steps=[('preprecessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('nominal',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(sparse=False))]),
                                                  ['city'])])),
                ('scaler', StandardScaler()),
                ('regressor', GradientBoostingRegressor())])

# #Results

In [24]:
y_pred=model.predict(x_test)

In [25]:
y_pred

array([ 677693.72645118,  383159.11594861,  341713.38004331, ...,
        635860.37111868,  340506.9146761 , 1404490.54361772])

In [28]:
np.sqrt(np.mean((y_test-y_pred)**2))

245713.26950983473