# Importing the Library

In [68]:
#importing numpy library
import numpy as np
#importing pandas library
import pandas as pd
#train_test_split
from sklearn.model_selection import train_test_split
#Ordinal and OnehotEncoder
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
#import ColumnTransformer
from sklearn.compose import ColumnTransformer
#for building pipeline
from sklearn.pipeline import Pipeline
#importing RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor

In [42]:
#loading the dataset
df=pd.read_json('/kaggle/input/netherlands-rent-properties/properties.json',lines=True)
#showing the dataset
df

,_id,externalId,areaRaw,areaSqm,city,coverImageUrl,crawlStatus,crawledAt,datesPublished,firstSeenAt,...,roommates,shower,smokingInside,toilet,userDisplayName,userId,userLastLoggedOn,userMemberSince,userPhotoUrl,additionalCostsDescription
0,{'$oid': '5d2b113a43cbfd7c77a998f4'},room-1686123,14 m2,14,Rotterdam,https://resources.kamernet.nl/image/913b4b03-5...,done,{'$date': '2019-07-26T22:18:23.018+0000'},"[{'$date': '2019-07-14T11:25:46.511+0000'}, {'...",{'$date': '2019-07-14T11:25:46.511+0000'},...,5,Shared,No,Shared,Huize west,4680711.0,21-07-2019,26-06-2019,https://resources.kamernet.nl/Content/images/s...,NaN
1,{'$oid': '5d2b113a43cbfd7c77a9991a'},studio-1691193,30 m2,30,Amsterdam,https://resources.kamernet.nl/image/5e11d6b5-8...,done,{'$date': '2019-08-10T22:28:46.099+0000'},"[{'$date': '2019-07-14T11:25:46.677+0000'}, {'...",{'$date': '2019-07-14T11:25:46.677+0000'},...,None,Own,No,Own,Cor,1865530.0,20-07-2019,05-01-2012,https://resources.kamernet.nl/Content/images/p...,NaN
2,{'$oid': '5d2b113a43cbfd7c77a99931'},room-1690545,11 m2,11,Amsterdam,https://resources.kamernet.nl/image/74b93a27-a...,done,{'$date': '2019-10-02T22:00:33.141+0000'},"[{'$date': '2019-07-14T11:25:46.834+0000'}, {'...",{'$date': '2019-07-14T11:25:46.834+0000'},...,1,Shared,Yes,Shared,Felix,4466569.0,20-07-2019,05-07-2018,https://resources.kamernet.nl/Content/images/p...,NaN
3,{'$oid': '5d2b113a43cbfd7c77a9994a'},room-1680036,16 m2,16,Assen,https://resources.kamernet.nl/image/84e95365-6...,done,{'$date': '2019-07-18T22:00:31.018+0000'},"[{'$date': '2019-07-14T11:25:46.988+0000'}, {'...",{'$date': '2019-07-14T11:25:46.988+0000'},...,4,Shared,Yes,Shared,Albert,783341.0,26-07-2019,09-11-2006,https://resources.kamernet.nl/Content/images/p...,NaN
4,{'$oid': '5d2b113b43cbfd7c77a9997c'},room-1691356,22 m2,22,Rotterdam,https://resources.kamernet.nl/Content/images/p...,done,{'$date': '2019-08-12T02:06:14.635+0000'},"[{'$date': '2019-07-14T11:25:47.193+0000'}, {'...",{'$date': '2019-07-14T11:25:47.193+0000'},...,1,Shared,No,Shared,John,3338401.0,19-07-2019,24-08-2014,https://resources.kamernet.nl/image/3177baf7-5...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46717,{'$oid': '5e5dada77fc8c93d83042924'},room-1774711,28 m2,28,Rotterdam,https://resources.kamernet.nl/image/198697b0-6...,done,{'$date': '2020-03-03T01:06:47.516+0000'},[{'$date': '2020-03-03T01:06:47.640+0000'}],{'$date': '2020-03-03T01:06:47.640+0000'},...,Unknown,Shared,No,Shared,Xandra,4490595.0,03-03-2020,08-08-2018,https://resources.kamernet.nl/image/1317498e-a...,NaN
46718,{'$oid': '5e5daddf7fc8c93d83043cfd'},room-1774600,16 m2,16,Harmelen,https://resources.kamernet.nl/image/8d75725a-d...,done,{'$date': '2020-03-03T01:07:43.775+0000'},[{'$date': '2020-03-03T01:07:43.898+0000'}],{'$date': '2020-03-03T01:07:43.898+0000'},...,2,Shared,No,Shared,Michel,4356840.0,24-02-2020,06-12-2017,https://resources.kamernet.nl/image/336ab03e-f...,NA
46719,{'$oid': '5e5dade07fc8c93d83043d2d'},room-1774595,30 m2,30,Rotterdam,https://resources.kamernet.nl/image/481fb7dd-a...,done,{'$date': '2020-03-03T01:07:43.947+0000'},[{'$date': '2020-03-03T01:07:44.071+0000'}],{'$date': '2020-03-03T01:07:44.071+0000'},...,Unknown,Shared,No,Shared,Xandra,4490595.0,02-03-2020,08-08-2018,https://resources.kamernet.nl/image/1317498e-a...,NaN
46720,{'$oid': '5e5dade27fc8c93d83043e7b'},room-1774582,35 m2,35,Rotterdam,https://resources.kamernet.nl/image/809ca8b1-c...,done,{'$date': '2020-03-03T01:07:45.950+0000'},[{'$date': '2020-03-03T01:07:46.072+0000'}],{'$date': '2020-03-03T01:07:46.072+0000'},...,6,Shared,No,Shared,Xandra,4490595.0,03-03-2020,08-08-2018,https://resources.kamernet.nl/image/1317498e-a...,NaN
46721,{'$oid': '5e5db1ad7fc8c93d8305b134'},studio-1765323,25 m2,25,Rotterdam,https://resources.kamernet.nl/image/203d5d86-9...,done,{'$date': '2020-03-03T01:23:57.716+0000'},[{'$date': '2020-03-03T01:23:57.836+0000'}],{'$date': '2020-03-03T01:23:57.836+0000'},...,None,Shared,No,Shared,Geert-Jan,4756677.0,02-03-2020,13-10-2019,https://resources.kamernet.nl/image/c609148f-e...,NA

# Checking for Preliminary Information

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46722 entries, 0 to 46721
Data columns (total 62 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   _id                          46722 non-null  object
 1   externalId                   46722 non-null  object
 2   areaRaw                      46722 non-null  object
 3   areaSqm                      46722 non-null  int64
 4   city                         46722 non-null  object
 5   coverImageUrl                46722 non-null  object
 6   crawlStatus                  46722 non-null  object
 7   crawledAt                    46722 non-null  object
 8   datesPublished               46722 non-null  object
 9   firstSeenAt                  46722 non-null  object
 10  furnish                      46722 non-null  object
 11  lastSeenAt                   46722 non-null  object
 12  latitude                     46722 non-null  float64
 13  longitude                    46722 non-null  float64
 14  postalCode                   46722 non-null  object
 15  postedAgo                    46722 non-null  object
 16  propertyType                 46722 non-null  object
 17  rawAvailability              46722 non-null  object
 18  rent                         46722 non-null  int64
 19  rentDetail                   46722 non-null  object
 20  rentRaw                      46722 non-null  object
 21  source                       46722 non-null  object
 22  title                        46722 non-null  object
 23  url                          46722 non-null  object
 24  additionalCosts              14301 non-null  float64
 25  additionalCostsRaw           46622 non-null  object
 26  deposit                      27704 non-null  float64
 27  depositRaw                   46622 non-null  object
 28  descriptionNonTranslated     46622 non-null  object
 29  descriptionNonTranslatedRaw  46622 non-null  object
 30  descriptionTranslated        46622 non-null  object
 31  descriptionTranslatedRaw     46622 non-null  object
 32  detailsCrawledAt             46722 non-null  object
 33  energyLabel                  46622 non-null  object
 34  gender                       45810 non-null  object
 35  internet                     46622 non-null  object
 36  isRoomActive                 46622 non-null  object
 37  kitchen                      46622 non-null  object
 38  living                       46622 non-null  object
 39  matchAge                     46622 non-null  object
 40  matchAgeBackup               46622 non-null  object
 41  matchCapacity                46622 non-null  object
 42  matchGender                  46622 non-null  object
 43  matchGenderBackup            46622 non-null  object
 44  matchLanguages               46622 non-null  object
 45  matchStatus                  46622 non-null  object
 46  matchStatusBackup            46622 non-null  object
 47  pageDescription              46622 non-null  object
 48  pageTitle                    46622 non-null  object
 49  pets                         46622 non-null  object
 50  registrationCost             4688 non-null   object
 51  registrationCostRaw          46622 non-null  object
 52  roommates                    45810 non-null  object
 53  shower                       46622 non-null  object
 54  smokingInside                46622 non-null  object
 55  toilet                       46622 non-null  object
 56  userDisplayName              46622 non-null  object
 57  userId                       46622 non-null  float64
 58  userLastLoggedOn             46622 non-null  object
 59  userMemberSince              46622 non-null  object
 60  userPhotoUrl                 46622 non-null  object
 61  additionalCostsDescription   20546 non-null  object
dtypes: float64(5), int64(2), object(55)
memory usage: 22.1+ MB

In [44]:
df.query("crawlStatus=='unavailable'")

,_id,externalId,areaRaw,areaSqm,city,coverImageUrl,crawlStatus,crawledAt,datesPublished,firstSeenAt,...,roommates,shower,smokingInside,toilet,userDisplayName,userId,userLastLoggedOn,userMemberSince,userPhotoUrl,additionalCostsDescription
77,{'$oid': '5d2b116743cbfd7c77a9a94b'},room-1691706,13 m2,13,Den Haag,https://resources.kamernet.nl/image/5b50a59e-c...,unavailable,{'$date': '2019-07-14T11:26:31.513+0000'},[{'$date': '2019-07-14T11:26:31.636+0000'}],{'$date': '2019-07-14T11:26:31.636+0000'},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,{'$oid': '5d2b116843cbfd7c77a9a9c8'},room-1691699,14 m2,14,Den Haag,https://resources.kamernet.nl/image/2fff4552-5...,unavailable,{'$date': '2019-07-16T06:02:01.690+0000'},"[{'$date': '2019-07-14T11:26:32.074+0000'}, {'...",{'$date': '2019-07-14T11:26:32.074+0000'},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,{'$oid': '5d2b117043cbfd7c77a9ac67'},room-1691664,20 m2,20,Ubbena,https://resources.kamernet.nl/image/6160f67d-5...,unavailable,{'$date': '2019-07-16T06:02:12.010+0000'},"[{'$date': '2019-07-14T11:26:40.809+0000'}, {'...",{'$date': '2019-07-14T11:26:40.809+0000'},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,{'$oid': '5d2b117c43cbfd7c77a9b0dd'},room-1685795,18 m2,18,Groningen,https://resources.kamernet.nl/image/3bd7fa60-b...,unavailable,{'$date': '2019-07-15T00:01:48.442+0000'},"[{'$date': '2019-07-14T11:26:52.485+0000'}, {'...",{'$date': '2019-07-14T11:26:52.485+0000'},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,{'$oid': '5d2b11bf43cbfd7c77a9cbc1'},room-1691430,10 m2,10,Haarlem,https://resources.kamernet.nl/Content/images/p...,unavailable,{'$date': '2019-07-17T22:11:12.102+0000'},"[{'$date': '2019-07-14T11:27:59.797+0000'}, {'...",{'$date': '2019-07-14T11:27:59.797+0000'},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43453,{'$oid': '5e4a7734f043235e654aad9d'},room-1763710,9 m2,9,Utrecht,https://resources.kamernet.nl/image/4bff92f2-5...,unavailable,{'$date': '2020-02-17T11:21:24.748+0000'},[{'$date': '2020-02-17T11:21:24.875+0000'}],{'$date': '2020-02-17T11:21:24.875+0000'},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44914,{'$oid': '5e5455b1f043235e65b4e1a9'},room-1772304,26 m2,26,Rotterdam,https://resources.kamernet.nl/image/63d56f67-a...,unavailable,{'$date': '2020-02-24T23:01:05.111+0000'},[{'$date': '2020-02-24T23:01:05.243+0000'}],{'$date': '2020-02-24T23:01:05.243+0000'},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45434,{'$oid': '5e56f8d9f043235e659c7136'},room-1773948,15 m2,15,Amsterdam,https://resources.kamernet.nl/Content/images/p...,unavailable,{'$date': '2020-02-26T23:01:45.598+0000'},[{'$date': '2020-02-26T23:01:45.765+0000'}],{'$date': '2020-02-26T23:01:45.765+0000'},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45492,{'$oid': '5e56f907f043235e659c9dd2'},apartment-1773816,120 m2,120,Nieuwerkerk a/d IJssel,https://resources.kamernet.nl/image/46cec33b-b...,unavailable,{'$date': '2020-03-03T01:13:06.666+0000'},"[{'$date': '2020-02-26T23:02:31.654+0000'}, {'...",{'$date': '2020-02-26T23:02:31.654+0000'},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45520,{'$oid': '5e56f915f043235e659ca8f9'},room-1773786,16 m2,16,Enschede,https://resources.kamernet.nl/image/f8de5216-6...,unavailable,{'$date': '2020-02-26T23:02:45.554+0000'},[{'$date': '2020-02-26T23:02:45.725+0000'}],{'$date': '2020-02-26T23:02:45.725+0000'},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Preprocessing Function

In [51]:
def preprocess_inputs(df):
    #creating copy of the dataset
    df=df.copy()
    #dropping bad rows
    bad_rows=df.query("crawlStatus=='unavailable'").index
    #dropping the bad_rows from the dataset
    df=df.drop(bad_rows,axis=0)
    
    
    
    
    #returning the dataset
    #selecting only useful column
    df=df[['areaSqm','city','furnish','latitude','propertyType',
          'rent','internet','kitchen','living','pets','shower','smokingInside','toilet']]
    #replacing missing and unknown with np.NaN
    df=df.replace({'':np.NaN,'Unknown':np.NaN})
    #replacing na with mode of that column
    
    for column in df.columns:
        df[column]=df[column].fillna(df[column].mode()[0])
    
    #splitting the data between x and y
    y=df['rent']
    x=df.drop('rent',axis=1)
    #train_test_split
    x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=1,shuffle=True)
    
    
    
    return x_train,x_test,y_train,y_test

In [52]:
x_train,x_test,y_train,y_test=preprocess_inputs(df)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(32635, 12)
(13987, 12)
(32635,)
(13987,)

In [54]:
x_test

,areaSqm,city,furnish,latitude,propertyType,internet,kitchen,living,pets,shower,smokingInside,toilet
31501,21,Groningen,Unfurnished,53.232598,Room,Yes,Shared,Shared,No,Shared,No,Shared
34546,50,Eindhoven,Furnished,51.426410,Apartment,Yes,Own,Own,No,Own,No,Own
42611,10,Leeuwarden,Unfurnished,53.184591,Room,Yes,Shared,Shared,No,Shared,No,Shared
36399,38,Nijmegen,Furnished,51.808167,Room,No,Shared,Own,No,Shared,No,Shared
43140,16,Amsterdam,Furnished,52.373412,Room,Yes,Shared,None,No,Own,Not important,Own
...,...,...,...,...,...,...,...,...,...,...,...,...
42232,110,Haarlem,Uncarpeted,52.383507,Apartment,No,Own,Own,No,Own,No,Own
36359,14,Amsterdam,Unfurnished,52.383644,Room,No,Shared,Shared,No,Shared,No,Shared
8004,51,Haarlem,Unfurnished,52.373505,Apartment,No,Own,Own,No,Own,No,Own
25144,22,Enschede,Unfurnished,52.220338,Room,Yes,Shared,None,No,Shared,Not important,Shared
15169,21,Arnhem,Unfurnished,51.981662,Room,Yes,Shared,Own,No,Shared,No,Shared

In [58]:
x_train

,areaSqm,city,furnish,latitude,propertyType,internet,kitchen,living,pets,shower,smokingInside,toilet
29882,61,Rotterdam,Unfurnished,51.925125,Apartment,Yes,Shared,Shared,No,Shared,No,Shared
44924,45,Rotterdam,Unfurnished,51.893369,Apartment,Yes,Own,Own,No,Own,No,Own
37182,105,Amsterdam,Furnished,52.376979,Apartment,Yes,Own,Own,No,Own,No,Own
13350,20,Delft,Uncarpeted,51.996010,Room,Yes,Shared,Shared,By mutual agreement,Shared,Not important,Shared
14736,44,Rotterdam,Furnished,51.891709,Apartment,Yes,Shared,Shared,No,Shared,No,Shared
...,...,...,...,...,...,...,...,...,...,...,...,...
43819,11,Enschede,Unfurnished,52.234413,Room,Yes,Shared,Shared,No,Shared,No,Shared
32602,21,Utrecht,Furnished,52.086425,Room,Yes,Shared,Shared,No,Shared,No,Shared
5254,16,Groningen,Furnished,53.229623,Room,Yes,Shared,Shared,No,Shared,No,Shared
12253,7,Utrecht,Furnished,52.102119,Room,Yes,Shared,None,No,Shared,No,Shared
33094,80,Utrecht,Furnished,52.096510,Apartment,Yes,Own,Own,No,Own,No,Own

In [ ]:
x_train[[]

In [62]:
{column:len(x_train[column].unique()) for column in x_train.columns if x_train[column].dtypes=='object'}

{'city': 663,
 'furnish': 3,
 'propertyType': 5,
 'internet': 2,
 'kitchen': 3,
 'living': 3,
 'pets': 3,
 'shower': 3,
 'smokingInside': 3,
 'toilet': 3}

In [83]:
ordinal_columns=['city','furnish','propertyType','living','kitchen','pets','shower','smokingInside','toilet']

In [56]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46622 entries, 0 to 46721
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   areaSqm        46622 non-null  int64
 1   city           46622 non-null  object
 2   furnish        46622 non-null  object
 3   latitude       46622 non-null  float64
 4   propertyType   46622 non-null  object
 5   rent           46622 non-null  int64
 6   internet       46622 non-null  object
 7   kitchen        46622 non-null  object
 8   living         46622 non-null  object
 9   pets           46622 non-null  object
 10  shower         46622 non-null  object
 11  smokingInside  46622 non-null  object
 12  toilet         46622 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 5.0+ MB

# Building PipeLine and Training

In [87]:
#tree models don't require scaling
binary_columns=['internet']
binary_transformation=Pipeline(steps=[('ordinal',OrdinalEncoder())])
onehot_transformation=Pipeline(steps=[('onehot',OneHotEncoder(sparse=False,handle_unknown='ignore'))])

preprocessing=ColumnTransformer(transformers=[('binary',binary_transformation,binary_columns),('onehot',onehot_transformation,ordinal_columns)],
                               remainder='passthrough')


model=Pipeline(steps=[('preprocesing',preprocessing),('regressor',RandomForestRegressor())])

# Training the Model with Train Set

In [88]:
model.fit(x_train,y_train)

Pipeline(steps=[('preprocesing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('binary',
                                                  Pipeline(steps=[('ordinal',
                                                                   OrdinalEncoder())]),
                                                  ['internet']),
                                                 ('onehot',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse=False))]),
                                                  ['city', 'furnish',
                                                   'propertyType', 'living',
                                                   'kitchen', 'pets', 'shower',
                                                   'smokingInside',
                                                   'toilet'])])),
                ('regressor', RandomForestRegressor())])

In [ ]:
Training the Model with Train Set

In [90]:
y_pred=model.predict(x_test)

In [99]:
print('Model Variation on Average',np.sqrt(np.mean((y_test-y_pred)**2)))

Model Variation on Average 163.29834101533416

In [97]:
print('Model r2 score',model.score(x_test,y_test))

Model r2 score 0.8443094066349082

# Checking for Missing Values

In [47]:
x.isna().sum()

areaSqm          0
city             0
furnish          0
latitude         0
propertyType     0
rent             0
internet         0
kitchen          0
living           0
pets             0
shower           0
smokingInside    0
toilet           0
dtype: int64

# Checking for Percentage of Missing Values in Each Column

In [48]:
x.isna().mean()

areaSqm          0.0
city             0.0
furnish          0.0
latitude         0.0
propertyType     0.0
rent             0.0
internet         0.0
kitchen          0.0
living           0.0
pets             0.0
shower           0.0
smokingInside    0.0
toilet           0.0
dtype: float64

# Checking For Mode for Each Column

In [49]:
for column in x.columns:
    mode={column:x[column].mode()[0]}
    print(mode)

{'areaSqm': 12}
{'city': 'Amsterdam'}
{'furnish': 'Furnished'}
{'latitude': 52.395059}
{'propertyType': 'Room'}
{'rent': 500}
{'internet': 'Yes'}
{'kitchen': 'Shared'}
{'living': 'Shared'}
{'pets': 'No'}
{'shower': 'Shared'}
{'smokingInside': 'No'}
{'toilet': 'Shared'}

# Checking for Unique Value in Each Column

In [50]:
{column:list(x[column].unique()) for column in x.columns if x[column].dtypes=='object'}

{'city': ['Rotterdam',
  'Amsterdam',
  'Assen',
  'Groningen',
  'Zeist',
  'Maastricht',
  'Callantsoog',
  'Alphen aan den Rijn',
  'Tilburg',
  'Enschede',
  'Leeuwarden',
  'Eindhoven',
  'Wageningen',
  'Diemen',
  'Utrecht',
  'Almere',
  'Alkmaar',
  'Harderwijk',
  'Hilversum',
  'Delft',
  'Den Bosch',
  'Stoutenburg',
  'Leiden',
  'Den Haag',
  'Boxtel',
  'Badhoevedorp',
  'Veenendaal',
  'Amstelveen',
  'Nijmegen',
  'Venlo',
  'Zwolle',
  'Ubbena',
  'Arnhem',
  'Leimuiden',
  'Riel',
  'Nieuwegein',
  'Haren Gn',
  'Uitgeest',
  'Beverwijk',
  'Ede',
  'Nijkerk',
  'Amersfoort',
  'Loosdrecht',
  'Apeldoorn',
  'Vaals',
  'Velp',
  'Vlaardingen',
  'Montfoort',
  'Heemstede',
  'Breda',
  'Purmerend',
  'Baarn',
  'Spijkenisse',
  'Deventer',
  'Hengelo',
  'Capelle aan den IJssel',
  'Bovenkarspel',
  'Weesp',
  'Harskamp',
  'Zeeland',
  'Waalre',
  'IJsselstein',
  'Pijnacker',
  'Sittard',
  'Putten',
  'Vlissingen',
  'Haarlem',
  'Rijswijk',
  'Zandvoort',
  'Zutphen',
  'Heerlen',
  'Breukeleveen',
  'Hoofddorp',
  'Hoensbroek',
  'Rosmalen',
  'Son en Breugel',
  'Etten-Leur',
  'Dordrecht',
  'Bergschenhoek',
  'Almelo',
  'Wijchen',
  'Zaandam',
  'Zoetermeer',
  'Gouda',
  'Oudorp',
  'Haule',
  'Uithoorn',
  'Oss',
  'Beuningen Gld',
  'Lelystad',
  'Houten',
  'Wenum Wiesel',
  'Warmenhuizen',
  'Hattem',
  'Schiedam',
  'Leerdam',
  'Hellevoetsluis',
  'Delden',
  'Veldhoven',
  'Best',
  'Leersum',
  'Twello',
  'Wassenaar',
  'De Bilt',
  'Oud-Beijerland',
  'Halfweg',
  'Vreeland',
  'Winterswijk',
  'Stadskanaal',
  'Heemskerk',
  'Ammerzoden',
  'Vries',
  'Voorburg',
  'Coevorden',
  'Wijk aan Zee',
  'Haelen',
  'Zaltbommel',
  'Bedum',
  'Werkhoven',
  'Sint Pancras',
  'Raamsdonksveer',
  'Hooghalen',
  'Moergestel',
  'Vinkeveen',
  'Beek (gem Ubbergen)',
  'Bunnik',
  'Cuijk',
  'Berg en Dal',
  'Barneveld',
  'Uden',
  'Keijenborg',
  'Roden',
  'Abcoude',
  'Wormerveer',
  'Katwijk',
  'Medemblik',
  'Valkenswaard',
  'Neerkant',
  'Wehl',
  'Weert',
  'Schermerhorn',
  'Gieten',
  'Geldrop',
  'Mierlo',
  'Roermond',
  'Bemmel',
  'Lisse',
  'Beneden-Leeuwen',
  'Berlicum',
  'Valkenburg',
  'Nuenen',
  'Leiderdorp',
  'Soest',
  'De Rijp',
  'Hattemerbroek',
  'Maassluis',
  'Maarssen',
  'Marsum',
  'Helmond',
  'Malden',
  'Cadier en Keer',
  'Hoorn',
  'Nieuwveen',
  'Slochteren',
  'Dongen',
  'Ouderkerk aan de Amstel',
  'Scherpenzeel',
  'Terneuzen',
  'Zoeterwoude',
  'Heeswijk-Dinther',
  'Sassenheim',
  'Voorschoten',
  'Oudehaske',
  'Peize',
  'Beilen',
  'Heesch',
  'Wierden',
  'Geleen',
  'Ommen',
  'IJmuiden',
  'Vijfhuizen',
  'Huizen',
  'Castricum',
  'Vrouwenparochie',
  'Emmen',
  'Doorn',
  'Hoevelaken',
  'Roelofarendsveen',
  'Zuidhorn',
  'Grou',
  'Zwaag',
  'Bussum',
  'Haaften',
  'Cromvoirt',
  'Zeddam',
  'Vught',
  'Budel',
  'Bunschoten-Spakenburg',
  'Venhorst',
  'Aalsmeer',
  'Smilde',
  'Nieuwe Pekela',
  'De Wilp',
  'Tolbert',
  'Termunterzijl',
  'Visvliet',
  'Elst',
  'Bennekom',
  'Leusden',
  'Lunteren',
  'Westervoort',
  'Doetinchem',
  'Oudenbosch',
  'Oudkarspel',
  'De Meern',
  'Exloo',
  'Voerendaal',
  'Dalfsen',
  'Hoogerheide',
  'Bilthoven',
  'Woerden',
  'Surhuizum',
  'Woubrugge',
  'Voorhout',
  'Eijsden',
  'Tegelen',
  'Sprang-Capelle',
  'Doorwerth',
  'Hoogeveen',
  'Eygelshoven',
  'Groenekan',
  'Dronten',
  'Nistelrode',
  'Duivendrecht',
  'Hoenderloo',
  'Meppel',
  'Noordwijk',
  'Roosendaal',
  'Olst',
  'Wateringen',
  'Dokkum',
  'Steenwijk',
  'Rijpwetering',
  'Hoogezand',
  'Den Helder',
  'Moordrecht',
  'Reusel',
  'Velsen-Noord',
  'Beekbergen',
  'Teuge',
  'Vianen',
  'Nieuwersluis',
  'Bentveld',
  'De Kwakel',
  'Barendrecht',
  'Kudelstaart',
  'Didam',
  'Baak',
  'Leuth',
  'Veendam',
  'Molenhoek',
  'Velserbroek',
  'Gronsveld',
  'Middenmeer',
  'Eerbeek',
  'Goirle',
  'Gaanderen',
  'Renkum',
  'Sliedrecht',
  'Oost West en Middelbeers',
  'Ewijk',
  'Geulle',
  'Puttershoek',
  'Belfeld',
  'Delfgauw',
  'Oosterbeek',
  'Lisserbroek',
  'Enkhuizen',
  'Mill',
  'Heumen',
  'Meerssen',
  'Nuland',
  'Loenen',
  'Huissen',
  'Heerenveen',
  'Dwingeloo',
  'Persingen',
  'Voorst',
  'Naarden',
  'Rheden',
  'Markelo',
  'Laren',
  'Rilland',
  'Groesbeek',
  'Zennewijnen',
  'Hasselt',
  'Vroomshoop',
  'Heino',
  'Elburg',
  'Nieuwleusen',
  'Hillegom',
  'Wijhe',
  'Oldenzaal',
  'Bunde',
  'Brunssum',
  'Venhuizen',
  "'s-Graveland",
  'Landgraaf',
  'Mander',
  'Oene',
  'Eersel',
  'Linden',
  'Veghel',
  'Buitenkaag',
  'Monnickendam',
  'Maarheeze',
  'Heel',
  'Kerkrade',
  'Oirschot',
  'Dieren',
  'Oisterwijk',
  'Haaksbergen',
  'Heeze',
  'Huisseling',
  'Kampen',
  'Harmelen',
  'Angerlo',
  'Goes',
  'Oostrum',
  'Oegstgeest',
  'Klazienaveen',
  'Baarlo (LB)',
  'Mijdrecht',
  'Ruinerwold',
  'Gemert',
  'Sappemeer',
  'Wagenberg',
  'Berkel-Enschot',
  'Staphorst',
  'Ermelo',
  'Leidschendam',
  'Nieuw-Vennep',
  'Deurne',
  'Werkendam',
  'Koog aan de Zaan',
  'Velp (NB)',
  'Wilnis',
  'Montfort',
  'Limmen',
  'Kerkdriel',
  'Assendelft',
  'Schoorl',
  'Oosterhout',
  'Foxhol',
  'Hoogvliet Rotterdam',
  'Rhenen',
  'Boxmeer',
  'Bavel',
  'Drempt',
  'Hummelo',
  'Zuiderwoude',
  'Kortenhoef',
  'Garderen',
  'Bemelen',
  'Rijsenhout',
  'Vaassen',
  'Lieshout',
  'Ulvenhout AC',
  'Rhenoy',
  'Waalwijk',
  'Nederweert',
  'Burgum',
  'Rijnsburg',
  'Katwijk NB',
  'Ridderkerk',
  'Groot-Ammers',
  'Winsum',
  'Wervershoof',
  'Nijensleek',
  'Zuidwolde',
  'Randwijk',
  'Klarenbeek',
  'Noordwijkerhout',
  'Zevenaar',
  'Hengevelde',
  'Appingedam',
  'Delfzijl',
  'Bergen (NH)',
  'Heerhugowaard',
  'Borger',
  'Wieringerwaard',
  'Odijk',
  'Koedijk',
  'Boksum',
  'Ingen',
  'Epse',
  'Voorthuizen',
  'Drachten',
  'Schijndel',
  'Soesterberg',
  'Culemborg',
  'Driebergen-Rijsenburg',
  'Heusden',
  'Zwijndrecht',
  'Ubbergen',
  'Rozenburg',
  'Wanneperveen',
  'Asten',
  'Epe',
  'Loenen aan de Vecht',
  'Schellinkhout',
  'Heerde',
  'Zevenbergen',
  'Eibergen',
  'Wolvega',
  'Opmeer',
  'Warmond',
  'Ressen',
  'Lathum',
  'Schipluiden',
  'Leende',
  'Hooge Zwaluwe',
  'Hoogland',
  'Goutum',
  'Wormer',
  'Zwanenburg',
  'Vlijmen',
  "'t Waar",
  'Bleskensgraaf ca',
  'Kockengen',
  'Ten Post',
  'Sint Odilienberg',
  'Musselkanaal',
  'de Lutte',
  'Waarland',
  'Albergen',
  'Budel-Dorplein',
  'Nunspeet',
  'Meerkerk',
  'Hoek van Holland',
  'Waddinxveen',
  'Eemnes',
  'Lage Zwaluwe',
  'Overloon',
  'Zeegse',
  'Loon op Zand',
  'Overveen',
  'Beinsdorp',
  'Deest',
  'Bosch en Duin',
  'Benthuizen',
  'Rijen',
  'Geffen',
  'Meteren',
  'Weurt',
  'Hardenberg',
  'Wapenveld',
  'Lith',
  'Zuidlaren',
  'Beuningen',
  'Maria Hoop',
  'Vleuten',
  'Wezep',
  'Tiendeveen',
  'Naaldwijk',
  'Boskoop',
  'Heteren',
  'Tiel',
  'Swifterbant',
  'Alblasserdam',
  'Merselo',
  'Vinkel',
  'Ambt Delden',
  'Sneek',
  'St. Willebrord',
  'Ankeveen',
  'Aalst',
  'Pernis Rotterdam',
  'Twijzel',
  'Stolwijk',
  'Herveld',
  'Haarsteeg',
  'Grave',
  'Brakel',
  'Bergen op Zoom',
  'Oost-Souburg',
  'Maren-Kessel',
  'Noordbroek',
  'Hem',
  'Mook',
  'Buitenpost',
  'Lopikerkapel',
  'Onstwedde',
  'Brantgum',
  'Tynaarlo',
  'Horn',
  'Tricht',
  'Stellendam',
  'Goedereede',
  'Egmond aan Zee',
  'Bad Nieuweschans',
  'Anloo',
  'Wamel',
  'Groenlo',
  'Wessem',
  'Edam',
  'Burgerbrug',
  'Raalte',
  'Heelsum',
  'Liempde',
  'Doesburg',
  'Koudekerk aan den Rijn',
  'Wittem',
  'Amerongen',
  'Sint Jansklooster',
  'Galder',
  'Wijk bij Duurstede',
  'Nijverdal',
  'Westzaan',
  'Middelburg',
  'Akkrum',
  'Plasmolen',
  'Lent',
  'Rijssen',
  'Heiloo',
  'Sint-Michielsgestel',
  'Leek',
  'Venray',
  'Simpelveld',
  'Gorinchem',
  'Maarn',
  'Nijeveen',
  'Schagen',
  'Mantinge',
  'Deursen-Dennenburg',
  'Dedemsvaart',
  'Bleiswijk',
  'Huis ter Heide',
  "'s-Gravenzande",
  'Melick',
  'Achterveld (UT)',
  'Woudenberg',
  'Hulshorst',
  'Woerdense Verlaat',
  'Hardinxveld-Giessendam',
  'Nootdorp',
  'Wesepe',
  'Berkel en Rodenrijs',
  'Gilze',
  'Hilvarenbeek',
  'Winssen',
  'Grootebroek',
  'Groet',
  'Heerewaarden',
  'Hazerswoude-Dorp',
  'Kamerik',
  'Gennep',
  'Kwintsheul',
  'Breukelen',
  'Sint Geertruid',
  'Warnsveld',
  'Kraggenburg',
  'Hooglanderveen',
  'Rheezerveen',
  'Wernhout',
  'Westerbroek',
  'Ysselsteyn',
  'Lochem',
  'Kolhorn',
  'Kesteren',
  'Colijnsplaat',
  'Bakel',
  'Nieuw-Balinge',
  'Made',
  'Aadorp',
  'Buggenum',
  'Krommenie',
  'Zaandijk',
  'Ameide',
  'Den Ilp',
  'Geldermalsen',
  'Nederhorst den Berg',
  'Egmond aan den Hoef',
  'Hendrik-Ido-Ambacht',
  'De Steeg',
  'Drongelen',
  'Kamperland',
  'Veeningen',
  'Sint-Oedenrode',
  'Zeewolde',
  'Ter Aar',
  'Den Ham (GR)',
  'Borne',
  'Etten',
  'Zwartsluis',
  'Drunen',
  'Landsmeer',
  'Stevensweert',
  'Herkenbosch',
  'Reeuwijk',
  'Hoogmade',
  'Hoeven',
  'Oud Gastel',
  'Kimswerd',
  'Lijnden',
  'Dorst',
  'Geeuwenbrug',
  'Garmerwolde',
  'Aduard',
  'Koudekerke',
  'Hall',
  'Langbroek',
  'Knegsel',
  'Berg en Terblijt',
  'Papendrecht',
  'Winterswijk Woold',
  'Lierop',
  'Nuth',
  'Blaricum',
  'Aarle-Rixtel',
  'Krimpen aan den IJssel',
  'Nieuwkuijk',
  'Axel',
  'Kropswolde',
  'Schalkwijk',
  'Westerland',
  'Vierhouten',
  'Duiven',
  'Tubbergen',
  'Schinveld',
  'Waardenburg',
  'Nieuwe Niedorp',
  'Oostvoorne',
  'Loenersloot',
  'Ospel',
  'Schalkhaar',
  'Gendt',
  'Margraten',
  'Kaatsheuvel',
  'Schin op Geul',
  'Hurdegaryp',
  'Vessem',
  'Eelde',
  'De Lier',
  'Jorwert',
  'Bergeijk',
  'Surhuisterveen',
  'Terborg',
  'Raamsdonk',
  'Marum',
  'Aldtsjerk',
  'Farmsum',
  'Vijlen',
  'Den Horn',
  "'t Goy",
  'Oudeschip',
  'Noordscheschut',
  'Zundert',
  'Barsingerhorn',
  'Oosthuizen',
  'Middenbeemster',
  'Cadzand',
  'Schaijk',
  'Zwammerdam',
  'Stiens',
  'Klundert',
  'Bocholtz',
  'Schoonhoven',
  "'t Harde",
  'Rijsbergen',
  'IJsselmuiden',
  'Aarlanderveen',
  'Biezenmortel',
  'Harkstede GN',
  'Wintelre',
  'Gulpen',
  'Boekel',
  'Berghem',
  'Oldehove',
  'Warffum',
  'Harlingen',
  'Avenhorn',
  'Purmerland',
  'Veenhuizen',
  'Winschoten',
  'Rhoon',
  'Oude Pekela',
  'Bitgummole',
  'Lopik',
  'Escharen',
  'Oude Meer',
  'Stein',
  'Deil',
  'Thesinge',
  'Prinsenbeek',
  'Franeker',
  'Herten',
  'Steensel',
  'Netersel',
  'Hoogkarspel',
  'Eethen',
  "'s-Heerenberg",
  'Austerlitz',
  'Nietap',
  'Otterlo',
  'Hedel',
  'Godlinze',
  'Elsloo',
  'Zierikzee',
  'Est',
  'Vasse',
  'Diessen',
  'Stieltjeskanaal',
  'Terheijden',
  'Broekhuizenvorst',
  'Bentelo',
  'Den Hoorn (ZH)',
  'Winkel',
  'Luyksgestel',
  'Born',
  'Geertruidenberg',
  'Blije',
  'Krimpen aan de Lek',
  'Liessel',
  'Genemuiden',
  'Rockanje',
  'Brielle',
  'amsterdam',
  'Kiel-Windeweer',
  'Rumpt',
  'Serooskerke',
  'Beek (LB)',
  'Kloosterburen',
  'Rekken',
  'Berltsum',
  'Benschop',
  'Elst Ut'],
 'furnish': ['Unfurnished', 'Furnished', 'Uncarpeted'],
 'propertyType': ['Room',
  'Studio',
  'Apartment',
  'Anti-squat',
  'Student residence'],
 'internet': ['Yes', 'No'],
 'kitchen': ['Shared', 'Own', 'None'],
 'living': ['None', 'Own', 'Shared'],
 'pets': ['No', 'Yes', 'By mutual agreement'],
 'shower': ['Shared', 'Own', 'None'],
 'smokingInside': ['No', 'Yes', 'Not important'],
 'toilet': ['Shared', 'Own', 'None']}