In [160]:
#importing numpy 
import numpy as np
#importing pandas 
import pandas as pd
#importing StandardScaler to scaling the dataset
from sklearn.preprocessing import StandardScaler
#importing train_test_split
from sklearn.model_selection import train_test_split
#importing tensorflow
import tensorflow as tf
#importing classification and confusion matrix
from sklearn.metrics import classification_report,confusion_matrix

In [161]:
#loading the datasset
df=pd.read_csv('/kaggle/input/noshowappointments/KaggleV2-May-2016.csv')
#showing the dataset
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [162]:
df['No-show'].value_counts()

No     88208
Yes    22319
Name: No-show, dtype: int64

In [163]:
#getting information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

# Cleaning

In [164]:
#checking for missing values
print('Total Missing Value',df.isna().sum().sum())

Total Missing Value 0

In [165]:
#checking for number of unique values
len(df['PatientId'].unique())

62299

In [166]:
#dropping patient id from the dataset
df=df.drop(['PatientId','AppointmentID'],axis=1)

In [167]:
#renaming the column name
df=df.rename(columns={'ScheduledDay':'ScheduleDate','AppointmentDay':'AppointmentDate'})

In [168]:
df

,Gender,ScheduleDate,AppointmentDate,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...
110522,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [169]:
df['ScheduleYear']=df['ScheduleDate'].apply(lambda x:np.int(x[0:4]))
df['ScheduleMonth']=df['ScheduleDate'].apply(lambda x:np.int(x[5:7]))
df['ScheduleDay']=df['ScheduleDate'].apply(lambda x:np.int(x[8:10]))
df['ScheduleHour']=df['ScheduleDate'].apply(lambda x:np.int(x[11:13]))
df['ScheduleMinute']=df['ScheduleDate'].apply(lambda x:np.int(x[14:16]))
df['ScheduleSecond']=df['ScheduleDate'].apply(lambda x:np.int(x[17:19]))
df=df.drop('ScheduleDate',axis=1)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  after removing the cwd from sys.path.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [170]:
df

,Gender,AppointmentDate,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show,ScheduleYear,ScheduleMonth,ScheduleDay,ScheduleHour,ScheduleMinute,ScheduleSecond
0,F,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No,2016,4,29,18,38,8
1,M,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No,2016,4,29,16,8,27
2,F,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No,2016,4,29,16,19,4
3,F,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,2016,4,29,17,29,31
4,F,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No,2016,4,29,16,7,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,F,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No,2016,5,3,9,15,35
110523,F,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No,2016,5,3,7,27,33
110524,F,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No,2016,4,27,16,3,52
110525,F,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No,2016,4,27,15,9,23
110526,F,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No,2016,4,27,13,30,56

In [171]:
df['AppointmentYear']=df['AppointmentDate'].apply(lambda x:np.int(x[0:4]))
df['AppointmentMonth']=df['AppointmentDate'].apply(lambda x:np.int(x[5:7]))
df['AppointmentDay']=df['AppointmentDate'].apply(lambda x:np.int(x[8:10]))


df=df.drop('AppointmentDate',axis=1)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until

In [172]:
df

,Gender,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show,ScheduleYear,ScheduleMonth,ScheduleDay,ScheduleHour,ScheduleMinute,ScheduleSecond,AppointmentYear,AppointmentMonth,AppointmentDay
0,F,62,JARDIM DA PENHA,0,1,0,0,0,0,No,2016,4,29,18,38,8,2016,4,29
1,M,56,JARDIM DA PENHA,0,0,0,0,0,0,No,2016,4,29,16,8,27,2016,4,29
2,F,62,MATA DA PRAIA,0,0,0,0,0,0,No,2016,4,29,16,19,4,2016,4,29
3,F,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,2016,4,29,17,29,31,2016,4,29
4,F,56,JARDIM DA PENHA,0,1,1,0,0,0,No,2016,4,29,16,7,23,2016,4,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,F,56,MARIA ORTIZ,0,0,0,0,0,1,No,2016,5,3,9,15,35,2016,6,7
110523,F,51,MARIA ORTIZ,0,0,0,0,0,1,No,2016,5,3,7,27,33,2016,6,7
110524,F,21,MARIA ORTIZ,0,0,0,0,0,1,No,2016,4,27,16,3,52,2016,6,7
110525,F,38,MARIA ORTIZ,0,0,0,0,0,1,No,2016,4,27,15,9,23,2016,6,7
110526,F,54,MARIA ORTIZ,0,0,0,0,0,1,No,2016,4,27,13,30,56,2016,6,7

# Encoding

In [173]:
#selecing only object columns
{column:list(df[column].unique()) for column in df.select_dtypes('object').columns}

{'Gender': ['F', 'M'],
 'Neighbourhood': ['JARDIM DA PENHA',
  'MATA DA PRAIA',
  'PONTAL DE CAMBURI',
  'REPÚBLICA',
  'GOIABEIRAS',
  'ANDORINHAS',
  'CONQUISTA',
  'NOVA PALESTINA',
  'DA PENHA',
  'TABUAZEIRO',
  'BENTO FERREIRA',
  'SÃO PEDRO',
  'SANTA MARTHA',
  'SÃO CRISTÓVÃO',
  'MARUÍPE',
  'GRANDE VITÓRIA',
  'SÃO BENEDITO',
  'ILHA DAS CAIEIRAS',
  'SANTO ANDRÉ',
  'SOLON BORGES',
  'BONFIM',
  'JARDIM CAMBURI',
  'MARIA ORTIZ',
  'JABOUR',
  'ANTÔNIO HONÓRIO',
  'RESISTÊNCIA',
  'ILHA DE SANTA MARIA',
  'JUCUTUQUARA',
  'MONTE BELO',
  'MÁRIO CYPRESTE',
  'SANTO ANTÔNIO',
  'BELA VISTA',
  'PRAIA DO SUÁ',
  'SANTA HELENA',
  'ITARARÉ',
  'INHANGUETÁ',
  'UNIVERSITÁRIO',
  'SÃO JOSÉ',
  'REDENÇÃO',
  'SANTA CLARA',
  'CENTRO',
  'PARQUE MOSCOSO',
  'DO MOSCOSO',
  'SANTOS DUMONT',
  'CARATOÍRA',
  'ARIOVALDO FAVALESSA',
  'ILHA DO FRADE',
  'GURIGICA',
  'JOANA D´ARC',
  'CONSOLAÇÃO',
  'PRAIA DO CANTO',
  'BOA VISTA',
  'MORADA DE CAMBURI',
  'SANTA LUÍZA',
  'SANTA LÚCIA',
  'BARRO VERMELHO',
  'ESTRELINHA',
  'FORTE SÃO JOÃO',
  'FONTE GRANDE',
  'ENSEADA DO SUÁ',
  'SANTOS REIS',
  'PIEDADE',
  'JESUS DE NAZARETH',
  'SANTA TEREZA',
  'CRUZAMENTO',
  'ILHA DO PRÍNCIPE',
  'ROMÃO',
  'COMDUSA',
  'SANTA CECÍLIA',
  'VILA RUBIM',
  'DE LOURDES',
  'DO QUADRO',
  'DO CABRAL',
  'HORTO',
  'SEGURANÇA DO LAR',
  'ILHA DO BOI',
  'FRADINHOS',
  'NAZARETH',
  'AEROPORTO',
  'ILHAS OCEÂNICAS DE TRINDADE',
  'PARQUE INDUSTRIAL'],
 'No-show': ['No', 'Yes']}

In [174]:
#creating function for encoding
def binary_encode(df,column,positive_value):
    df=df.copy()
    df[column]=df[column].apply(lambda x:1 if x==positive_value else 0)
    return df

In [175]:
def onehot_encode(df,column,prefix):
    df=df.copy()
    dummies=pd.get_dummies(df[column],prefix=prefix)
    df=pd.concat([df,dummies],axis=1)
    df=df.drop(column,axis=1)
    return df

In [176]:
df=binary_encode(df,'Gender','M')
df=binary_encode(df,'No-show','Yes')

In [179]:
df=onehot_encode(df,'Neighbourhood','N')

In [180]:
df

,Gender,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show,ScheduleYear,...,N_SANTOS REIS,N_SEGURANÇA DO LAR,N_SOLON BORGES,N_SÃO BENEDITO,N_SÃO CRISTÓVÃO,N_SÃO JOSÉ,N_SÃO PEDRO,N_TABUAZEIRO,N_UNIVERSITÁRIO,N_VILA RUBIM
0,0,62,0,1,0,0,0,0,0,2016,...,0,0,0,0,0,0,0,0,0,0
1,1,56,0,0,0,0,0,0,0,2016,...,0,0,0,0,0,0,0,0,0,0
2,0,62,0,0,0,0,0,0,0,2016,...,0,0,0,0,0,0,0,0,0,0
3,0,8,0,0,0,0,0,0,0,2016,...,0,0,0,0,0,0,0,0,0,0
4,0,56,0,1,1,0,0,0,0,2016,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,0,56,0,0,0,0,0,1,0,2016,...,0,0,0,0,0,0,0,0,0,0
110523,0,51,0,0,0,0,0,1,0,2016,...,0,0,0,0,0,0,0,0,0,0
110524,0,21,0,0,0,0,0,1,0,2016,...,0,0,0,0,0,0,0,0,0,0
110525,0,38,0,0,0,0,0,1,0,2016,...,0,0,0,0,0,0,0,0,0,0
110526,0,54,0,0,0,0,0,1,0,2016,...,0,0,0,0,0,0,0,0,0,0

# Spliting and Scaling the Dataset

In [181]:
y=df['No-show']
x=df.drop('No-show',axis=1)

# Scaling the Dataset with StandardScaler

In [182]:
scaler=StandardScaler()
x=pd.DataFrame(scaler.fit_transform(x),columns=x.columns)

# train test

In [184]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7)

x_train.shape

In [185]:
x_train.shape

(77368, 98)

# Training with Tensorflow

In [187]:
inputs=tf.keras.Input(shape=(98,))
x=tf.keras.layers.Dense(64,activation='relu')(inputs)
x=tf.keras.layers.Dense(64,activation='relu')(x)
outputs=tf.keras.layers.Dense(1,activation='sigmoid')(x)

2023-01-07 05:47:04.073754: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.

# Creating the Model

In [188]:
model=tf.keras.Model(inputs,outputs)

# Compiling the model

In [190]:
model.compile(optimizer='adam',loss='binary_crossentropy',
             metrics=['accuracy',tf.keras.metrics.AUC(name='auc')])

# Fitting the Model

In [192]:
history=model.fit(x_train,y_train,validation_split=0.2,batch_size=32,
                 epochs=100,callbacks=[tf.keras.callbacks.EarlyStopping(
                 monitor='val_loss',patience=3,restore_best_weights=True)])

2023-01-07 05:52:24.092525: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)

Epoch 1/100
1935/1935 [==============================] - 5s 2ms/step - loss: 0.4849 - accuracy: 0.7973 - auc: 0.6403 - val_loss: 0.4779 - val_accuracy: 0.7927 - val_auc: 0.6744
Epoch 2/100
1935/1935 [==============================] - 4s 2ms/step - loss: 0.4680 - accuracy: 0.7994 - auc: 0.6835 - val_loss: 0.4706 - val_accuracy: 0.7936 - val_auc: 0.6941
Epoch 3/100
1935/1935 [==============================] - 4s 2ms/step - loss: 0.4607 - accuracy: 0.7992 - auc: 0.7011 - val_loss: 0.4661 - val_accuracy: 0.7942 - val_auc: 0.7036
Epoch 4/100
1935/1935 [==============================] - 4s 2ms/step - loss: 0.4556 - accuracy: 0.8010 - auc: 0.7115 - val_loss: 0.4651 - val_accuracy: 0.7942 - val_auc: 0.7063
Epoch 5/100
1935/1935 [==============================] - 4s 2ms/step - loss: 0.4515 - accuracy: 0.8017 - auc: 0.7195 - val_loss: 0.4647 - val_accuracy: 0.7933 - val_auc: 0.7092
Epoch 6/100
1935/1935 [==============================] - 4s 2ms/step - loss: 0.4472 - accuracy: 0.8024 - auc: 0.7280 - val_loss: 0.4654 - val_accuracy: 0.7943 - val_auc: 0.7111
Epoch 7/100
1935/1935 [==============================] - 4s 2ms/step - loss: 0.4438 - accuracy: 0.8032 - auc: 0.7339 - val_loss: 0.4622 - val_accuracy: 0.7951 - val_auc: 0.7132
Epoch 8/100
1935/1935 [==============================] - 4s 2ms/step - loss: 0.4404 - accuracy: 0.8033 - auc: 0.7406 - val_loss: 0.4629 - val_accuracy: 0.7933 - val_auc: 0.7138
Epoch 9/100
1935/1935 [==============================] - 4s 2ms/step - loss: 0.4376 - accuracy: 0.8052 - auc: 0.7450 - val_loss: 0.4639 - val_accuracy: 0.7930 - val_auc: 0.7120
Epoch 10/100
1935/1935 [==============================] - 4s 2ms/step - loss: 0.4346 - accuracy: 0.8058 - auc: 0.7503 - val_loss: 0.4623 - val_accuracy: 0.7932 - val_auc: 0.7136

# Result

In [193]:
model.evaluate(x_test,y_test)

1037/1037 [==============================] - 1s 1ms/step - loss: 0.4631 - accuracy: 0.7976 - auc: 0.7039

[0.4630816876888275, 0.7976115345954895, 0.703852653503418]

In [183]:
x

,Gender,Age,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,ScheduleYear,ScheduleMonth,...,N_SANTOS REIS,N_SEGURANÇA DO LAR,N_SOLON BORGES,N_SÃO BENEDITO,N_SÃO CRISTÓVÃO,N_SÃO JOSÉ,N_SÃO PEDRO,N_TABUAZEIRO,N_UNIVERSITÁRIO,N_VILA RUBIM
0,-0.733837,1.077932,-0.330112,2.017378,-0.278261,-0.177068,-0.137722,-0.687612,0.023691,-1.150983,...,-0.070524,-0.036244,-0.065279,-0.114853,-0.129969,-0.134955,-0.150499,-0.170773,-0.03711,-0.088086
1,1.362701,0.818306,-0.330112,-0.495693,-0.278261,-0.177068,-0.137722,-0.687612,0.023691,-1.150983,...,-0.070524,-0.036244,-0.065279,-0.114853,-0.129969,-0.134955,-0.150499,-0.170773,-0.03711,-0.088086
2,-0.733837,1.077932,-0.330112,-0.495693,-0.278261,-0.177068,-0.137722,-0.687612,0.023691,-1.150983,...,-0.070524,-0.036244,-0.065279,-0.114853,-0.129969,-0.134955,-0.150499,-0.170773,-0.03711,-0.088086
3,-0.733837,-1.258708,-0.330112,-0.495693,-0.278261,-0.177068,-0.137722,-0.687612,0.023691,-1.150983,...,-0.070524,-0.036244,-0.065279,-0.114853,-0.129969,-0.134955,-0.150499,-0.170773,-0.03711,-0.088086
4,-0.733837,0.818306,-0.330112,2.017378,3.593747,-0.177068,-0.137722,-0.687612,0.023691,-1.150983,...,-0.070524,-0.036244,-0.065279,-0.114853,-0.129969,-0.134955,-0.150499,-0.170773,-0.03711,-0.088086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,-0.733837,0.818306,-0.330112,-0.495693,-0.278261,-0.177068,-0.137722,1.454309,0.023691,0.246060,...,-0.070524,-0.036244,-0.065279,-0.114853,-0.129969,-0.134955,-0.150499,-0.170773,-0.03711,-0.088086
110523,-0.733837,0.601950,-0.330112,-0.495693,-0.278261,-0.177068,-0.137722,1.454309,0.023691,0.246060,...,-0.070524,-0.036244,-0.065279,-0.114853,-0.129969,-0.134955,-0.150499,-0.170773,-0.03711,-0.088086
110524,-0.733837,-0.696184,-0.330112,-0.495693,-0.278261,-0.177068,-0.137722,1.454309,0.023691,-1.150983,...,-0.070524,-0.036244,-0.065279,-0.114853,-0.129969,-0.134955,-0.150499,-0.170773,-0.03711,-0.088086
110525,-0.733837,0.039425,-0.330112,-0.495693,-0.278261,-0.177068,-0.137722,1.454309,0.023691,-1.150983,...,-0.070524,-0.036244,-0.065279,-0.114853,-0.129969,-0.134955,-0.150499,-0.170773,-0.03711,-0.088086
110526,-0.733837,0.731763,-0.330112,-0.495693,-0.278261,-0.177068,-0.137722,1.454309,0.023691,-1.150983,...,-0.070524,-0.036244,-0.065279,-0.114853,-0.129969,-0.134955,-0.150499,-0.170773,-0.03711,-0.088086