<a href="https://www.kaggle.com/code/vijays140291/woman-active-prediction?scriptVersionId=153371960" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
#loading the dataset
df=pd.read_csv('/kaggle/input/top-women-chess-players/top_women_chess_players_aug_2020.csv')
#loading the dataset
df

,Fide id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
0,700070,"Polgar, Judit",HUN,F,1976.0,GM,2675,2646.0,2736.0,wi
1,8602980,"Hou, Yifan",CHN,F,1994.0,GM,2658,2621.0,2601.0,NaN
2,5008123,"Koneru, Humpy",IND,F,1987.0,GM,2586,2483.0,2483.0,NaN
3,4147103,"Goryachkina, Aleksandra",RUS,F,1998.0,GM,2582,2502.0,2441.0,NaN
4,700088,"Polgar, Susan",HUN,F,1969.0,GM,2577,NaN,NaN,wi
...,...,...,...,...,...,...,...,...,...,...
8548,3302288,"Reinkens, Natalia",BOL,F,NaN,NaN,1801,NaN,NaN,wi
8549,343960,"Saffova, Michaela",CZE,F,1994.0,NaN,1801,1791.0,1765.0,NaN
8550,5038294,"Shetye, Siddhali",IND,F,1992.0,NaN,1801,1884.0,1824.0,wi
8551,2072491,"Trakru, Priya",USA,F,2001.0,WFM,1801,NaN,NaN,wi
8552,4666399,"Vorpahl, Sina Fleur",GER,F,1982.0,NaN,1801,NaN,NaN,wi

In [3]:
#Preprocessing the dataset

#dropping the fide id and name


df=df.drop(['Fide id','Name','Gender'],axis=1)
df

,Federation,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
0,HUN,1976.0,GM,2675,2646.0,2736.0,wi
1,CHN,1994.0,GM,2658,2621.0,2601.0,NaN
2,IND,1987.0,GM,2586,2483.0,2483.0,NaN
3,RUS,1998.0,GM,2582,2502.0,2441.0,NaN
4,HUN,1969.0,GM,2577,NaN,NaN,wi
...,...,...,...,...,...,...,...
8548,BOL,NaN,NaN,1801,NaN,NaN,wi
8549,CZE,1994.0,NaN,1801,1791.0,1765.0,NaN
8550,IND,1992.0,NaN,1801,1884.0,1824.0,wi
8551,USA,2001.0,WFM,1801,NaN,NaN,wi
8552,GER,1982.0,NaN,1801,NaN,NaN,wi

In [4]:
#Missing values

df.isna().sum()

Federation            0
Year_of_birth       292
Title              5435
Standard_Rating       0
Rapid_rating       4945
Blitz_rating       5081
Inactive_flag      2701
dtype: int64

In [5]:
#checking for datatype

df.dtypes

Federation          object
Year_of_birth      float64
Title               object
Standard_Rating      int64
Rapid_rating       float64
Blitz_rating       float64
Inactive_flag       object
dtype: object

In [6]:
numerical_columns=[column for column in df.columns if df[column].dtypes!='object']

In [7]:
numerical_columns

['Year_of_birth', 'Standard_Rating', 'Rapid_rating', 'Blitz_rating']

In [8]:
for column in numerical_columns:
    df[column]=df[column].fillna(df[column].mean())

In [9]:
df['Title'].unique()

array(['GM', 'IM', 'WGM', 'FM', 'WFM', 'WIM', nan, 'CM', 'WCM', 'WH'],
      dtype=object)

In [10]:
df['Inactive_flag'].unique()

array(['wi', nan], dtype=object)

In [11]:
df['Inactive_flag']=df['Inactive_flag'].fillna('wa')

In [12]:
df

,Federation,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
0,HUN,1976.000000,GM,2675,2646.000000,2736.000000,wi
1,CHN,1994.000000,GM,2658,2621.000000,2601.000000,wa
2,IND,1987.000000,GM,2586,2483.000000,2483.000000,wa
3,RUS,1998.000000,GM,2582,2502.000000,2441.000000,wa
4,HUN,1969.000000,GM,2577,1931.680155,1925.155242,wi
...,...,...,...,...,...,...,...
8548,BOL,1985.291732,NaN,1801,1931.680155,1925.155242,wi
8549,CZE,1994.000000,NaN,1801,1791.000000,1765.000000,wa
8550,IND,1992.000000,NaN,1801,1884.000000,1824.000000,wi
8551,USA,2001.000000,WFM,1801,1931.680155,1925.155242,wi
8552,GER,1982.000000,NaN,1801,1931.680155,1925.155242,wi

In [13]:
title_dummies=pd.get_dummies(df['Title'])

In [14]:
df=pd.concat([df,title_dummies['GM']],axis=1)

In [15]:
#dropping the title column
df=df.drop('Title',axis=1)

In [16]:
df['GM']=df['GM'].astype(int)

In [17]:
df

,Federation,Year_of_birth,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag,GM
0,HUN,1976.000000,2675,2646.000000,2736.000000,wi,1
1,CHN,1994.000000,2658,2621.000000,2601.000000,wa,1
2,IND,1987.000000,2586,2483.000000,2483.000000,wa,1
3,RUS,1998.000000,2582,2502.000000,2441.000000,wa,1
4,HUN,1969.000000,2577,1931.680155,1925.155242,wi,1
...,...,...,...,...,...,...,...
8548,BOL,1985.291732,1801,1931.680155,1925.155242,wi,0
8549,CZE,1994.000000,1801,1791.000000,1765.000000,wa,0
8550,IND,1992.000000,1801,1884.000000,1824.000000,wi,0
8551,USA,2001.000000,1801,1931.680155,1925.155242,wi,0
8552,GER,1982.000000,1801,1931.680155,1925.155242,wi,0

In [18]:
encoder=LabelEncoder()
df['Inactive_flag']=encoder.fit_transform(df['Inactive_flag'])

In [19]:
#dropping the federation column
df=df.drop('Federation',axis=1)

In [20]:
df

,Year_of_birth,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag,GM
0,1976.000000,2675,2646.000000,2736.000000,1,1
1,1994.000000,2658,2621.000000,2601.000000,0,1
2,1987.000000,2586,2483.000000,2483.000000,0,1
3,1998.000000,2582,2502.000000,2441.000000,0,1
4,1969.000000,2577,1931.680155,1925.155242,1,1
...,...,...,...,...,...,...
8548,1985.291732,1801,1931.680155,1925.155242,1,0
8549,1994.000000,1801,1791.000000,1765.000000,0,0
8550,1992.000000,1801,1884.000000,1824.000000,1,0
8551,2001.000000,1801,1931.680155,1925.155242,1,0
8552,1982.000000,1801,1931.680155,1925.155242,1,0

In [21]:
#splitting the dataset
y=df['GM']
x=df.drop('GM',axis=1)

In [22]:
x

,Year_of_birth,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
0,1976.000000,2675,2646.000000,2736.000000,1
1,1994.000000,2658,2621.000000,2601.000000,0
2,1987.000000,2586,2483.000000,2483.000000,0
3,1998.000000,2582,2502.000000,2441.000000,0
4,1969.000000,2577,1931.680155,1925.155242,1
...,...,...,...,...,...
8548,1985.291732,1801,1931.680155,1925.155242,1
8549,1994.000000,1801,1791.000000,1765.000000,0
8550,1992.000000,1801,1884.000000,1824.000000,1
8551,2001.000000,1801,1931.680155,1925.155242,1
8552,1982.000000,1801,1931.680155,1925.155242,1

In [23]:
scaler=StandardScaler()
x=pd.DataFrame(scaler.fit_transform(x),columns=x.columns)

In [24]:
#train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=123)

In [25]:
#train_test_split
from sklearn.linear_model import LogisticRegression

In [26]:
model=LogisticRegression()
model.fit(x_train,y_train)
print('The model accuracy is',model.score(x_test,y_test))

The model accuracy is 0.9984411535463756