<a href="https://www.kaggle.com/code/vijays140291/world-university-ranking?scriptVersionId=138382827" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
#importing library
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
#loading the dataset
df=pd.read_csv('/kaggle/input/world-university-rankings-202223/2023 QS World University Rankings.csv')
#loading the dataset
df

,Rank,institution,location code,location,ar score,ar rank,er score,er rank,fsr score,fsr rank,...,cpf rank,ifr score,ifr rank,isr score,isr rank,irn score,irn rank,ger score,ger rank,score scaled
0,1,Massachusetts Institute of Technology (MIT),US,United States,100.0,5,100.0,4,100.0,14,...,5,100.0,54,90.0,109,96.1,58,100.0,3,100
1,2,University of Cambridge,UK,United Kingdom,100.0,2,100.0,2,100.0,11,...,55,100.0,60,96.3,70,99.5,6,100.0,9,98.8
2,3,Stanford University,US,United States,100.0,4,100.0,5,100.0,6,...,9,99.8,74,60.3,235,96.3,55,100.0,2,98.5
3,4,University of Oxford,UK,United Kingdom,100.0,3,100.0,3,100.0,8,...,64,98.8,101,98.4,54,99.9,3,100.0,7,98.4
4,5,Harvard University,US,United States,100.0,1,100.0,1,99.4,35,...,2,76.9,228,66.9,212,100.0,1,100.0,1,97.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1417,1418,Universidad Nacional Autónoma de Honduras (UNAH),HN,Honduras,4.6,501+,5.8,501+,3.6,601+,...,601+,1.7,601+,NaN,NaN,8.1,601+,NaN,NaN,-
1418,1419,Universidad Tecnológica de Bolívar,CO,Colombia,3.0,501+,5.8,501+,2.4,601+,...,601+,9.3,601+,1.3,601+,8.8,601+,30.9,403,-
1419,1420,Université Mohammed V de Rabat,MA,Morocco,2.8,501+,2.6,501+,3.2,601+,...,601+,5.2,601+,2.8,601+,51.1,601+,NaN,NaN,-
1420,1421,University of Craiova,RO,Romania,3.3,501+,1.8,501+,2.7,601+,...,601+,NaN,NaN,NaN,NaN,7.5,601+,8.7,601+,-
1421,1422,University of Oradea,RO,Romania,4.0,501+,2.1,501+,3.3,601+,...,601+,1.7,601+,7.9,601+,16.6,601+,9.7,601+,-

In [3]:
df.columns

Index(['Rank', 'institution', 'location code', 'location', 'ar score',
       'ar rank', 'er score', 'er rank', 'fsr score', 'fsr rank', 'cpf score',
       'cpf rank', 'ifr score', 'ifr rank', 'isr score', 'isr rank',
       'irn score', 'irn rank', 'ger score', 'ger rank', 'score scaled'],
      dtype='object')

In [4]:
df.isna().sum()

Rank              0
institution       0
location code     0
location          0
ar score          0
ar rank           0
er score          1
er rank           0
fsr score         2
fsr rank          0
cpf score         5
cpf rank          0
ifr score        98
ifr rank         98
isr score        57
isr rank         57
irn score        13
irn rank         13
ger score        12
ger rank         12
score scaled      0
dtype: int64

In [5]:
object_columns=[column for column in df.columns if df[column].dtype=='object']

In [6]:
object_columns_rank=object_columns[3:]

In [7]:
object_columns_rank

['ar rank',
 'er rank',
 'fsr rank',
 'cpf rank',
 'ifr rank',
 'isr rank',
 'irn rank',
 'ger rank',
 'score scaled']

In [8]:
import numpy as np

for column in object_columns_rank:
    # Step 1: Remove '+' character from values
    df[column] = df[column].apply(lambda x: x.replace('+', '') if isinstance(x, str) and '+' in x else x)

    # Step 2: Convert the column to float if possible
    df[column] = pd.to_numeric(df[column], errors='coerce')  # Set non-numeric values to NaN

    # Step 3: Fill missing values with the mean of the column
    df[column] = df[column].fillna(df[column].mean())

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1422 entries, 0 to 1421
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           1422 non-null   int64
 1   institution    1422 non-null   object
 2   location code  1422 non-null   object
 3   location       1422 non-null   object
 4   ar score       1422 non-null   float64
 5   ar rank        1422 non-null   int64
 6   er score       1421 non-null   float64
 7   er rank        1422 non-null   int64
 8   fsr score      1420 non-null   float64
 9   fsr rank       1422 non-null   int64
 10  cpf score      1417 non-null   float64
 11  cpf rank       1422 non-null   int64
 12  ifr score      1324 non-null   float64
 13  ifr rank       1422 non-null   float64
 14  isr score      1365 non-null   float64
 15  isr rank       1422 non-null   float64
 16  irn score      1409 non-null   float64
 17  irn rank       1422 non-null   float64
 18  ger score      1410 non-null   float64
 19  ger rank       1422 non-null   float64
 20  score scaled   1422 non-null   float64
dtypes: float64(13), int64(5), object(3)
memory usage: 233.4+ KB

In [10]:
df

,Rank,institution,location code,location,ar score,ar rank,er score,er rank,fsr score,fsr rank,...,cpf rank,ifr score,ifr rank,isr score,isr rank,irn score,irn rank,ger score,ger rank,score scaled
0,1,Massachusetts Institute of Technology (MIT),US,United States,100.0,5,100.0,4,100.0,14,...,5,100.0,54.000000,90.0,109.000000,96.1,58.0,100.0,3.00000,100.0000
1,2,University of Cambridge,UK,United Kingdom,100.0,2,100.0,2,100.0,11,...,55,100.0,60.000000,96.3,70.000000,99.5,6.0,100.0,9.00000,98.8000
2,3,Stanford University,US,United States,100.0,4,100.0,5,100.0,6,...,9,99.8,74.000000,60.3,235.000000,96.3,55.0,100.0,2.00000,98.5000
3,4,University of Oxford,UK,United Kingdom,100.0,3,100.0,3,100.0,8,...,64,98.8,101.000000,98.4,54.000000,99.9,3.0,100.0,7.00000,98.4000
4,5,Harvard University,US,United States,100.0,1,100.0,1,99.4,35,...,2,76.9,228.000000,66.9,212.000000,100.0,1.0,100.0,1.00000,97.6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1417,1418,Universidad Nacional Autónoma de Honduras (UNAH),HN,Honduras,4.6,501,5.8,501,3.6,601,...,601,1.7,601.000000,NaN,468.912088,8.1,601.0,NaN,473.12766,44.6194
1418,1419,Universidad Tecnológica de Bolívar,CO,Colombia,3.0,501,5.8,501,2.4,601,...,601,9.3,601.000000,1.3,601.000000,8.8,601.0,30.9,403.00000,44.6194
1419,1420,Université Mohammed V de Rabat,MA,Morocco,2.8,501,2.6,501,3.2,601,...,601,5.2,601.000000,2.8,601.000000,51.1,601.0,NaN,473.12766,44.6194
1420,1421,University of Craiova,RO,Romania,3.3,501,1.8,501,2.7,601,...,601,NaN,464.759819,NaN,468.912088,7.5,601.0,8.7,601.00000,44.6194
1421,1422,University of Oradea,RO,Romania,4.0,501,2.1,501,3.3,601,...,601,1.7,601.000000,7.9,601.000000,16.6,601.0,9.7,601.00000,44.6194

In [11]:
df.isna().sum()

Rank              0
institution       0
location code     0
location          0
ar score          0
ar rank           0
er score          1
er rank           0
fsr score         2
fsr rank          0
cpf score         5
cpf rank          0
ifr score        98
ifr rank          0
isr score        57
isr rank          0
irn score        13
irn rank          0
ger score        12
ger rank          0
score scaled      0
dtype: int64

In [12]:
for column in [column for column in df.columns if df[column].dtype!='object'][1:]:
    df[column]=df[column].fillna(df[column].mean())

In [13]:
df.isna().sum()

Rank             0
institution      0
location code    0
location         0
ar score         0
ar rank          0
er score         0
er rank          0
fsr score        0
fsr rank         0
cpf score        0
cpf rank         0
ifr score        0
ifr rank         0
isr score        0
isr rank         0
irn score        0
irn rank         0
ger score        0
ger rank         0
score scaled     0
dtype: int64

In [14]:
for column in [column for column in df.columns if df[column].dtype=='object']:
    encode=LabelEncoder()
    df[column]=encode.fit_transform(df[column])

In [15]:
y=df['Rank']
x=df.drop('Rank',axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=123)

In [16]:
scaler=StandardScaler()
scaler.fit(x_train)
x_train=pd.DataFrame(scaler.transform(x_train),columns=x_train.columns)
x_test=pd.DataFrame(scaler.transform(x_test),columns=x_test.columns)

In [17]:
model=LinearRegression()
model.fit(x_train,y_train)
print(model.score(x_test,y_test))

0.9299652965376448

In [18]:
list(model.predict(x_test))[0:10]

[1167.5765529122755,
 1173.8277898639406,
 1097.6928888204995,
 1001.1976642842267,
 245.43319148989735,
 -84.25121318351876,
 1036.9763964255135,
 1086.0833982211934,
 834.0085575443749,
 943.1709290986232]

In [19]:
list(y_test)[0:10]

[1183, 1405, 922, 953, 321, 36, 971, 1110, 588, 1121]